### ISSUE TITLE
Problem while running "python3 setup.py build_ext --inplace"

### ISSUE THREAD

**Issue by abhimanyu-jain** [zju3dv/pvnet#100]
Python version : 3.5.2

pip3 list shows setuptools version 41.4.0   as installed.

But when I run "python3 setup.py build_ext --inplace", I get the following error:

Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named 'setuptools'

**Comment by pengsida** [comment]
You could google how to resolve this problem.
