### ISSUE TITLE
issue: python build_extend_utils_cffi.py

### ISSUE THREAD

**Issue by futurev** [zju3dv/pvnet#101]
os: ubuntu
gpu: GeForce GTX 1080
cuda: 9.0

os.system('nvcc src/nearest_neighborhood.cu -c -o src/nearest_neighborhood.cu.o -x cu -Xcompiler -fPIC -O2 -arch=sm_52 -I {} -D_FORCE_INLINES'.
          format(cuda_include))

could not be able to generate nearest_neighborhood.cu.o.

**Comment by pengsida** [comment]
Please detailed error messages.

**Comment by futurev** [comment]
solved
