### ISSUE TITLE
LINEMOD mask

### ISSUE THREAD

**Issue by JokerShao** [zju3dv/pvnet#102]
请问LINEMOD真实图像有用作训练吗？
下载的数据集里有mask，但ORIG里面并没有mask信息，那么它们的mask是如何得到的呢？通过LINEMOD_ORIG里面的深度信息做截断吗？

我们这边想自定义物体训练，有了render图像和fuse图像，渲染合成的训练集和测试集都还不错，但是在真实相机中效果不好（已经针对相机修改过内参数），你们有遇到这个问题吗？

**Comment by pengsida** [comment]
1. 我们有用真实图像做训练。
2. mask可以通过opengl渲染得到。
3. 如果只用渲染的图片，需要要用detection，效果会好一些。

**Comment by JokerShao** [comment]
好的，十分感谢！
