### ISSUE TITLE
question about annotations of images created with cut-and-paste (fuse) approach

### ISSUE THREAD

**Issue by GiuliaP** [zju3dv/pvnet#106]
Hi,

I am visualizing the annotations of the images produced by using the `fuse` approach from `pvnet-rendering` code and I am not able to visualize correct annotations. Specifically, I am using the projection code from the function [validate_pose](https://github.com/zju3dv/pvnet/blob/master/lib/utils/data_utils.py#L914) (with paths and reading data functions adapted to work on `fuse` images). 

As far as I understood from the code, it seems to me that these pose annotations are loaded from the foreground image and copied to the generated image (in the [prepare_dataset_single](https://github.com/zju3dv/pvnet-rendering/blob/master/fuse/fuse.py#220) function). However, since the position of the object on the image changes when pasting it to the background image (in [fuse_regions](https://github.com/zju3dv/pvnet-rendering/blob/master/fuse/fuse.py#L243)), I would like to know where in the code the annotation (only translation?) is modified accordingly.

**Comment by pengsida** [comment]
We revise the camera intrinsics of the fuse images at https://github.com/zju3dv/pvnet/blob/master/lib/utils/data_utils.py#L321

**Comment by GiuliaP** [comment]
@pengsida Thanks for the quick reply! Yes, I saw that point in the code. However, I am asking where (and if), in the code, the translation annotation of the fuse image is computed, accounting for the fact that the object segmented from the foreground and then pasted on the the background, has a different (randomly sampled) position on the image plane, than the one it had on the original image from where it was cropped. Hence, the translation annotation for the object on the fuse image should be different from the translation annotation of the same object in the original foreground image.

**Comment by pengsida** [comment]
We randomly paste an object to the image at https://github.com/zju3dv/pvnet-rendering/blob/master/fuse/fuse.py#L243
The translation is stored at `begins` to revise the camera intrinsics.
You could also revise the object pose and keep the intrinsics unchanged.

**Comment by GiuliaP** [comment]
Thanks for the clarification, I am sorry I could not understand at the beginning that you are revising the intrinsics rather than the pose annotations. Can I ask you the reason for this choice? Thanks again for the quick replies.

**Comment by pengsida** [comment]
I also do not know.
Maybe my partner thought that it is better to revise the camera intrinsics.

**Comment by sherwoac** [comment]
> Thanks for the clarification, I am sorry I could not understand at the beginning that you are revising the intrinsics rather than the pose annotations. Can I ask you the reason for this choice? Thanks again for the quick replies.

I solved this by:
- using the 'adjusted' intrinsics according to the offsets in the {n}_info.pkl[0][object_index]:
            blender_intrinsic_matrix[0, 2] += offset_rc[1]
            blender_intrinsic_matrix[1, 2] += offset_rc[0]
            blender_intrinsic_matrix[0, 0] *= 0.85
            blender_intrinsic_matrix[1, 1] *= 0.85
to project the 3d bounding box points using the extrinsic in the {n}_info.pkl[1][object_index] file, giving 2d image coordinates
- solving pnp using:
     the original (consistent) intrinsic_matrix['linemod'] intrinsic
     the 2d image coordinates from the projection above
     the same 3d bounding box
