### ISSUE TITLE
3D keypoints data for other models

### ISSUE THREAD

**Issue by donghoonsagong** [zju3dv/pvnet#107]
Dear pengsida, 

Thank you for sharing your work.

For the 3d reference keypoint, I could find the file "cat_points_3d.txt"  (for "cat" model)

How can I get a reference keypoints for other model such as can ("can_points_3d.txt")? 

Thank you!

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet#compute-fps-keypoints
