### ISSUE TITLE
Error while executing 'python lib/utils/data_utils.py'

### ISSUE THREAD

**Issue by pjw1** [zju3dv/pvnet#108]
Hi, thank you for your kind tutorial.

I found an error while executing
'python lib/utils/data_utils.py'
for computing FPS keypoints.

The error code is as following

/Desktop/pvnet/lib/utils$ python data_utils.py
Traceback (most recent call last):
  File "data_utils.py", line 19, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/Desktop/pvnet/lib/utils/extend_utils/extend_utils.py", line 4, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ModuleNotFoundError: No module named 'lib.utils.extend_utils._extend_utils'

I check that there are _extend_utils.c and extend_utils.py in extend_utils folder and both code don't include lib and ffi functions.
I wonder how can I get those functions.

Thank you very much for the excellent paper!

**Comment by pengsida** [comment]
Compile the extensions first.
![image](https://user-images.githubusercontent.com/11582122/69790909-52fe8a00-11fe-11ea-8dc3-26d6f286bd9d.png)

**Comment by pjw1** [comment]
Ok,
I just found that I had some errors while doing compiling extension_utils because of my ubuntu version. 
Thanks for help!
closed
