### ISSUE TITLE
[Errno 2] No such file or directory:pvnet/data/OCCLUSION_LINEMOD/masks/cat/0.png

### ISSUE THREAD

**Issue by bringBackm** [zju3dv/pvnet#11]
Hi, l meet this problem and check out the OCCLUSION_LINEMOD Dataset, there isn't a masks dir, so ..? what's this problem?
Thank you!

**Comment by pengsida** [comment]
I omitted a procedure to generate the masks.
But data in the masks directory is not useful.
Please tell me where the wrong messages came out, and I will update the code or upload the procedure to generate the masks.

**Comment by bringBackm** [comment]
File "tools/train_linemod.py", line 359, in <module>
    train_net()
  File "tools/train_linemod.py", line 346, in train_net
    val(net, occ_val_loader, epoch, 'occ_val',use_motion=motion_model)
  File "tools/train_linemod.py", line 187, in val
    for idx, data in enumerate(dataloader):

It looks like the mask is needed for data.

**Comment by pengsida** [comment]
I have updated README. Please see https://github.com/zju3dv/pvnet#generate-masks

**Comment by bringBackm** [comment]
Fine, it all works.
Thank you for your great work.
It takes me a lot of time for running these codes and installing dependencies, especially generating the masks.
And some suggestions for this repo:  maybe it can have a requirement.txt or setup.py for people to quickly install all essential things and the masks can be uploaded to the online dataset zip for people to download.

**Comment by pengsida** [comment]
Thank you for your suggestions. I will provide a requirement.txt and update the dataset.
Thank you!
