### ISSUE TITLE
How to find the 6D pose if the 3d Ground truth box is not given

### ISSUE THREAD

**Issue by sunit1409** [zju3dv/pvnet#110]
In this approach is there any means to guess the 3d bbox of the object or the complete 6D pose of the object without having the ground truth box.

**Comment by pengsida** [comment]
The ground truth 6d pose is defined on a 3d model.
If there is no a 3d model, we could alternatively predict a predefined 3d bbox for the target object, which is called 3d detection.
VoteNet solves the problem of 3d detection in a way similar to our approach.

**Comment by sunit1409** [comment]
@pengsida actually what I am trying to ask is this    , here https://github.com/zju3dv/pvnet/blob/master/tools/demo.py#L179   you are doing a pnp to obtain the 6d pose [x,y,z, yaw, pitch, roll] of the object, can the model take the image and directly predict the 6d pose without having to do PNP.

**Comment by pengsida** [comment]
No.

**Comment by sunit1409** [comment]
Alright @pengsida thanks for the update. It is a really wonderful work.
