### ISSUE TITLE
How to change the setting in the multi gpu?

### ISSUE THREAD

**Issue by kevin860213** [zju3dv/pvnet#111]
I have trained the network successful in single gpu, but i want to train in multi gpu to train it faster. But, i don't know how to change the code or parameter , can you tell me how do you do in 4 gpus? thanks

**Comment by pengsida** [comment]
If your machine is equiped with four gpus, it will automatically use four gpus.
Use `CUDA_VISIBLE_DEVICES="0, 1, 2, 3"` to choose which gpus to use.

**Comment by kevin860213** [comment]
But,i don't know why i got this error.
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
I check my gpus, which like this
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:1C:00.0 Off |                    0 |
| N/A   30C    P0    42W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:B2:00.0 Off |                    0 |
| N/A   37C    P0    44W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:DB:00.0 Off |                    0 |
| N/A   34C    P0    42W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:DC:00.0 Off |                    0 |
| N/A   32C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |

**Comment by pengsida** [comment]
I don't know what caused this problem.
You could google for it.
One example is: https://discuss.pytorch.org/t/shm-error-in-docker/22755

**Comment by kevin860213** [comment]
I change the num_works, and it works.
Thanks you very much
