### ISSUE TITLE
uncertainty_pnp

### ISSUE THREAD

**Issue by AingLee** [zju3dv/pvnet#112]
Hi, Sida, running the code with using only the PnP is working fine for me, but not with the uncertainty_PnP. I got the error "Segmentation fault (core dumped)" and when I just tried to figure out that error, it seemed to be related to uncertainty_pnp.cpp file. Can you check it again or do you have any suggestions to solve this error? Thanks

**Comment by pengsida** [comment]
Ceres solver causes this problem.
You need to try other version of ceres solver.

**Comment by AingLee** [comment]
Thank you for your reply, and I am sorry for not responding. now my current ceres solver version is 1.14.0, so I need to downgrade it, right? How do I know which ceres solver version is compatible with this implementation? To reinstall the ceres solver with other version, can I just modify the version stated in "build_ceres.sh" file? Thanks

**Comment by pengsida** [comment]
I am not familiar with ceres, so I do not know.
