### ISSUE TITLE
Whether the network can train multiple objects at the same time

### ISSUE THREAD

**Issue by RhodaLiu17** [zju3dv/pvnet#113]
Recently, I am doing some research on 6D pose estimation. And I find your results are very good. So I download your code and try to do some tests. But then I find that I can only train one object at one time, which confuses me. The paper says your segmentation ouput channal is C+1. So I am wondering whether you have tested on training multi-class objects at the same time. If you have had, could you tell me the results? I am looking forward to your reply, thanks!

**Comment by pengsida** [comment]
1. We did not train multi-class objects on linemod, since linemod annotates one object per image.
2. You could train the multi-class objects on your custom dataset.
