### ISSUE TITLE
LINEMOD_ORIG/data/depth.dpt

### ISSUE THREAD

**Issue by jinglan0829** [zju3dv/pvnet#114]
How to read depth.dpt file in LINEMOD_ORIG and what is it? How can I create custom model for .dpt file? Thank you!

**Comment by pengsida** [comment]
We did not create depth.dpt. It comes from the original dataset.

**Comment by jinglan0829** [comment]
谢谢作者的回复，我想使用自己的模型实现pvnet，所以想要创建相同的linemod_dataset, 但是不知道该如何构造自己模型的original dataset，是不需要这些数据集吗？ 只要有模型的image, corresponding poses,masks就可以实现pvnet吗？

**Comment by pengsida** [comment]
对的，只要模型的image, poses和masks，还有预定义好的关键点，就可以做pvnet。如果可以，我这周末会放一个干净版本的pvnet。

**Comment by jinglan0829** [comment]
好的，谢谢！等待作者的更新！预定义好的关键点是FPS key points吗？ 想要training自己的模型也是就需要这些吗？

**Comment by pengsida** [comment]
是的。

**Comment by jinglan0829** [comment]
好的好的，谢谢！

**Comment by pengsida** [comment]
@jinglan0829 我们放了干净版本的pvnet。
里面有读取depth用来做icp refinement：https://github.com/zju3dv/clean-pvnet/blob/4a144caacb8a0403d3d6931d02b2097e036c5190/lib/utils/img_utils.py#L9
里面也有在自己数据集训练的例子：https://github.com/zju3dv/clean-pvnet#training-on-the-custom-object

**Comment by jinglan0829** [comment]
好的，谢谢作者，我训练了自己的数据集以后，想要检测是否准确，该如何像python run.py --type visualize --cfg_file configs/linemod.yaml model cat一样查看呢？是需要自己编程吗？还有想问一下如何使最后输出的结果是包含Rotation和Translation的矩阵呢？（这方面不是很懂，望作者体谅）

**Comment by pengsida** [comment]
直接用这个命令，但需要设置自己的model name。具体命令行意思可以看这里https://github.com/zju3dv/clean-pvnet/blob/master/project_structure.md#training-and-testing
最后输出的结果在https://github.com/zju3dv/clean-pvnet/blob/master/lib/evaluators/linemod/pvnet.py#L97

**Comment by pengsida** [comment]
我补充了在自己数据集上的可视化和evaluation：https://github.com/zju3dv/clean-pvnet/blob/master/README.md#training-on-the-custom-object
如果有问题，请在新仓库提issue

**Comment by jinglan0829** [comment]
好的好的，非常感谢！！！
