### ISSUE TITLE
多目标自制数据集

### ISSUE THREAD

**Issue by dyh-bupt** [zju3dv/pvnet#115]
您好，LINEMOD数据集中每张图片仅有一个待识别目标。如果我想将pvnet应用到”一张图片有多个待识别目标“的情况中，我应该如何操作呢？
PS：我目前拥有数千张RGB图像以及所有待识别目标的3D模型，以及相机参数

**Comment by pengsida** [comment]
把semantic segmentation改成c+1通道就可以。

**Comment by pengsida** [comment]
我重新整理了代码，里面有教怎么在自制数据集上进行训练
https://github.com/zju3dv/clean-pvnet

**Comment by dyh-bupt** [comment]
非常感谢您的回答和教程，我会认真去学习一下的，赞！
