### ISSUE TITLE
Do we need to train the network per each object category?

### ISSUE THREAD

**Issue by sh8** [zju3dv/pvnet#116]
Hi,
Thank you very much for making the codes publicly available!

According to the paper, it seems that the network does not need to be trained per object category.
Could you let me know the reason why you adopted a category-separated training scheme in your codes?

**Comment by sh8** [comment]
https://github.com/zju3dv/pvnet/issues/113

**Comment by pengsida** [comment]
We have released a cleaner version of  pvnet: https://github.com/zju3dv/clean-pvnet
You could prepare the multi-class objects by editing https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/linemod/linemod_to_coco.py
And change the network a little.
