### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.utils'

### ISSUE THREAD

**Issue by zhuqianqian-judy** [zju3dv/pvnet#119]
您好，我是一个初学者。
我用的Readme中Another way is to use the following commands.
当运行data_utils.py，出现下面的错。
Traceback (most recent call last):
  File "data_utils.py", line 17, in <module>
      from lib.utils.config import cfg
ModuleNotFoundError: No module named 'lib.utils'

并且在运行另一个.py文件时，也出现ModuleNotFoundError: No module named 'lib.networks'

您能帮我看看这个问题吗？十分感谢。

**Comment by pengsida** [comment]
需要使用python3。
需要运行`python lib/utils/data_utils.py`，不能运行`python data_utils.py`。
建议使用https://github.com/zju3dv/clean-pvnet

**Comment by zhuqianqian-judy** [comment]
是用的python3,也是运行python lib/utils/data_utils.py，按照您readme中的步骤做的，但是还是会出现上述的问题。

**Comment by pengsida** [comment]
我看data_utils.py里面有把路径加到python path里呀，我这里运行没问题。
你是用python3.7吗

**Comment by zhuqianqian-judy** [comment]
是的 python3.7 ，服务器 ubuntu是16.04，gcc5.4

**Comment by pengsida** [comment]
这个比较神奇了，python的module调用不同版本不一样。
建议你用https://github.com/zju3dv/clean-pvnet
这个代码应该没这问题。

**Comment by zhuqianqian-judy** [comment]
行，好的。那我去看看clean-pvnet。谢谢你啦。

**Comment by zhuqianqian-judy** [comment]
reqirements.txt中，opencv_contrib_python==3.4.2.17   scikit_image==0.16.2   numpy==1.14.5，我改了一下这三个的版本，因为之前按照您的那个，安装不了。这个对后期工作没有影响吧？

**Comment by pengsida** [comment]
scikit_image可能会有影响。
你用清华源，应该是可以装的。直接pip install -r requirements.txt.

**Comment by zhuqianqian-judy** [comment]
好的，我再看看。谢谢

**Comment by emilychen6160** [comment]
@zqq-judy 您好，請問這個問題有解決方案嗎？
