### ISSUE TITLE
libceres.so.2: undefined symbol

### ISSUE THREAD

**Issue by nuannuanhcc** [zju3dv/pvnet#120]
Hi, 
Thanks for sharing your great work!
When I run  lib/utils/data_utils.py, there is an error:

Traceback (most recent call last):
  File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: /home/pvnet/lib/utils/extend_utils/lib/libceres.so.2: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev

Note that previous processes are compiled without errors, and I have added the lib under extend_utils to the LD_LIBRARY_PATH.

Are there any suggestions about that? My environment is Ubuntu 16.04+gcc 5.4.0+cuda 9.0.

Thanks again.

**Comment by pengsida** [comment]
You have imported the ceres successfully, but the protobuf version on your computer is likely not compatible with ceres.
If you do not intend to use uncertainty pnp, you could use https://github.com/zju3dv/clean-pvnet

**Comment by nuannuanhcc** [comment]
Thanks for your reply！
However, I want to use the uncertainty pnp. And my protoc version is libprotoc 2.6.1. Do you know how to get the compatible version？

**Comment by pengsida** [comment]
The core problem is how to use the ceres library on your computer.
