### ISSUE TITLE
RuntimeError: CUDA out of memory error

### ISSUE THREAD

**Issue by MehwishG** [zju3dv/pvnet#121]
Hi pengssida,
thanks for sharing the code. I am facing cuda out of memory error during training:
$python3 tools/train_linemod.py --cfg_file configs/linemod_train.json --linemod_cls cat
 
 I am training the network on Geforce GTX 1080 Ti 
I will be looking forward to your reply.

![Screenshot from 2020-01-23 11-34-48](https://user-images.githubusercontent.com/53044443/72981478-b4238380-3d91-11ea-8ff0-d6b8bb329f1a.png)

**Comment by pengsida** [comment]
Reduce the batch size in `configs/linemod_train.json`.

**Comment by MehwishG** [comment]
Resolved. Thank you
