### ISSUE TITLE
Pretrained model for multiple objects

### ISSUE THREAD

**Issue by padeler** [zju3dv/pvnet#122]
Thank you for the work. 

Do you provide pretrainned weights for multiple objects? The "download model" folder only contains models for specific objects.

**Comment by pengsida** [comment]
I did not train our network on multiple objects.

**Comment by padeler** [comment]
Thank you for the quick reply. Is it possible to train it for multiple objects and get the expected accuracy or is it better to use one model for each class on the same image in order to detect everything?

**Comment by pengsida** [comment]
It is possible to train it for multiple objects and get a similar accuracy using a bigger network.

**Comment by padeler** [comment]
Hello again, thanks for the quick reply. 

I am wondering what changes would be needed to make it work for multiple objects? Should I only change the backbone to something bigger (i.e resnet50) or should I also change the front of the network or use higher resolution or more keypoints per object? 

thanks in advance!

**Comment by pengsida** [comment]
You probably need a bigger network.
And you need to revise the output channels for semantic segmentation.
