### ISSUE TITLE
Creating a customized 6dof dataset.

### ISSUE THREAD

**Issue by ishangupta3** [zju3dv/pvnet#124]
In the creation of a brand new 6dof dataset what would be the best way to collect the ground truth for the pose - (Rt matrix)? 

I understand that the qr codes (markers)  help provide that ground truth, but what if during inference the qr codes are not present? Any details or input on the creation of a customized 6dof dataset will be helpful. 

I have seen this repo: https://github.com/F2Wang/ObjectDatasetTools - but it does not go into detail for retrieving the Rt matrix.

**Comment by pengsida** [comment]
I know about two ways:
1. https://github.com/F2Wang/ObjectDatasetTools
2. First define a set of 3d keypoints, then manually annotate the 2d keypoints, and finally use PnP to solve the pose.

**Comment by ishangupta3** [comment]
@pengsida  I am able to manually extract the translation and rotation. Can I use that method instead?

**Comment by pengsida** [comment]
Yes.
Organize the dataset as the structured described in https://github.com/zju3dv/clean-pvnet#training-on-the-custom-object

**Comment by 571502680** [comment]
大佬们有没有兴趣加一下位姿估计交流群：756535271，欢迎大佬莅临指导！！！

**Comment by ishangupta3** [comment]
> 大佬们有没有兴趣加一下位姿估计交流群：756535271，欢迎大佬莅临指导！！！

How can I join the group?
