### ISSUE TITLE
Several problems

### ISSUE THREAD

**Issue by g185211** [zju3dv/pvnet#126]
1. 所给代码并未用到UN-PNP，而是直接用的solve解算器，对吗？
def pnp(points_3d, points_2d, camera_matrix,method=cv2.SOLVEPNP_ITERATIVE)
2. 两像素矢量交点产生关键点假设，逐像素对所有假设点投票，选出得分较高的假设点作为关键点，对吗？
3.用这个算法去检测一张图像时，需要“图像，最远采样法得出的3D点，训练出的模型”，就可以了吗？
非常谢谢，期待您的回答！

**Comment by pengsida** [comment]
1. 可以选择uncertainty-driven PnP.
2. 对的。
2. 对的。
