### ISSUE TITLE
3D关键点的2D坐标是怎么找到的？

### ISSUE THREAD

**Issue by yimingli1998** [zju3dv/pvnet#128]
您好，看了论文之后有个疑惑，烦请指教。计算loss时用的ground truth vector，我的理解是FPS采样得到的关键点在2D图像上的坐标，这个坐标是怎么得到的呢？如果关键点在2D图像中被挡住了，这个ground truth还准确吗？

**Comment by pengsida** [comment]
FPS采样得到3d关键点，将3d关键点投影到2d图像得到2d关键点。

**Comment by yimingli1998** [comment]
> FPS采样得到3d关键点，将3d关键点投影到2d图像得到2d关键点。

嗯，那如果投影到2D的关键点被别的点挡住了呢？

**Comment by pengsida** [comment]
不影响。

**Comment by Zephyr-One** [comment]
在测试阶段场景物体的3D坐标怎么获得呢
