### ISSUE TITLE
Fuse Dataset included in training of network

### ISSUE THREAD

**Issue by MehwishG** [zju3dv/pvnet#129]
Thank you for this amazing work.
As you have mentioned in paper, 10,000 synthetic rendered images were used for training of PVNet. Also, pvnet is trained for each object separately.Did you included fuse dataset (for all objects)too for training pvnet ?

**Comment by MehwishG** [comment]
Line: https://github.com/zju3dv/pvnet/blob/master/lib/utils/data_utils.py#L304 shows fuse dataset is used for training but during smooth l1 loss: vertex_weight is getting mask information for each object while we are training our network for one object e.g. cat..Fuse images looks like following:
![1000_rgb](https://user-images.githubusercontent.com/53044443/83947073-333fc280-a82e-11ea-8eea-ecf16cbb130e.jpg)

**Comment by pengsida** [comment]
pvnet is also trained for each object separately on the fuse dataset.

**Comment by MehwishG** [comment]
Thanks for reply. Can you please clear one thing. In following function: https://github.com/zju3dv/pvnet/blob/master/lib/datasets/linemod_dataset.py#L68, xy contains pixel locations of every object (in case of fuse dataset).?
And pvnet is trained for each object by combining (Linemod,rendered, fusion) data.?

**Comment by MehwishG** [comment]
Hi, thanks 
I debugged the code and resolved my confusion.
