### ISSUE TITLE
compile ransac_voting

### ISSUE THREAD

**Issue by gaobaoding** [zju3dv/pvnet#13]
Hallo, I have problems with compilation of ransac_voting. I use python3.6, pytorch0.4.1 and gcc5.4.0.

(pvnet) gaobaoding@gaobaoding-T5:~/pvnet$ python tools/demo.py
Traceback (most recent call last):
  File "tools/demo.py", line 8, in <module>
    from lib.ransac_voting_gpu_layer.ransac_voting_gpu import ransac_voting_layer_v3
  File "/home/ning/pvnet/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 2, in <module>
    import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting
ImportError: /home/ning/pvnet/lib/ransac_voting_gpu_layer/ransac_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

**Comment by pengsida** [comment]
It works to add `import torch` before `import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting`.

**Comment by robotSunGina** [comment]
> Hallo, I have problems with compilation of ransac_voting. I use python3.6, pytorch0.4.1 and gcc5.4.0.
> 
> (pvnet) gaobaoding@gaobaoding-T5:~/pvnet$ python tools/demo.py
> Traceback (most recent call last):
> File "tools/demo.py", line 8, in
> from lib.ransac_voting_gpu_layer.ransac_voting_gpu import ransac_voting_layer_v3
> File "/home/ning/pvnet/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 2, in
> import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting
> ImportError: /home/ning/pvnet/lib/ransac_voting_gpu_layer/ransac_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

I met the same problem, have you solve this problem? thanks for your reply.

**Comment by jason2718** [comment]
Same problem here. Any ideas?

**Comment by pengsida** [comment]
It is difficult for me to guess what problem

**Comment by WilliamKRobert** [comment]
Downgrading pytorch to 0.4.1 solves my problem.

**Comment by monajalal** [comment]
@pengsida  I have the same problem I have provided the full details here. `import torch` is already above it. https://github.com/chensong1995/HybridPose/issues/88
