### ISSUE TITLE
Is there a script to add files to LINEMOD_ORIG to transform to LINEMOD? 

### ISSUE THREAD

**Issue by greatwallet** [zju3dv/pvnet#130]
Hi! 
Currently I am not able to access OneDrive to download `LINEMOD`, but I have downloaded original Linemod, i.e. `LINEMOD_ORIG`, from HINTERSTOISSER's website. So I wonder if there is any file that IS in `LINEMOD`  but NOT in `LINEMOD_ORIG`, and how could I add them into `LINEMOD_ORIG`?

For example, I have linked `LINEMOD` to `LINEMOD_ORIG` by 
```
cd /path/to/pvnet/data
ln -s LINEMOD_ORG LINEMOD
cd ..
``` 
and I tried run `python lib/data/utils/data_utils.py` to run FPS. However, I noticed that `LINEMOD_ORIG` seemed to be missing "dense_pts.txt", so how could I add "dense_pts.txt" to `LINEMOD_ORIG` by mesh models? Also, is there any other file just like "dense_pts.txt" that I should manually add by myself?

**Comment by pengsida** [comment]
No.
The object poses in two dataset are defined on different object coordinate frames.
