### ISSUE TITLE
请问怎么去淘宝打印linemod的3d 模型

### ISSUE THREAD

**Issue by JZhao12** [zju3dv/pvnet#134]
I bought it from 3d print shop at taobao.

_Originally posted by @pengsida in https://github.com/zju3dv/pvnet/issues/72#issuecomment-527002431_

大佬你好，我想问一下，我是要自己建模然后创建 .stl文件然后发给淘宝，还是直接告诉淘宝我想要打印linemod数据集的模型就好了？如果方便的话，可以发我一下淘宝链接吗😀谢谢大佬

**Comment by pengsida** [comment]
不是我打印的。
你问问淘宝的店家就知道的。
