### ISSUE TITLE
dense_pts.txt

### ISSUE THREAD

**Issue by emilychen6160** [zju3dv/pvnet#135]
Dear author:
Thank you for your pvnet package!
Can I ask what the function of "dense_pts.txt is"? 
Moreover, how many types of training data format needed to prepare if we want to train a model of ourselves like ape in LINEMOD or other object,etc.
Thank you!

**Comment by pengsida** [comment]
`dense_pts.txt` is the mesh vertices.

**Comment by emilychen6160** [comment]
Therefore, if we want to train the model of us, can we follow the LINEMOD dataset you povide to change details of each file?

**Comment by pengsida** [comment]
Yes.

**Comment by emilychen6160** [comment]
thank you~

**Comment by emilychen6160** [comment]
There is also a question that "demo.py" can not run with the error:"RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411". I have saw the related question, but we use the RTX 2080 and pytorch looks no problem.

**Comment by emilychen6160** [comment]
There is also a question that "demo.py" can not run with the error:"RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411". I have seen the related question, but we use the RTX 2080 and pytorch looks no problem.
