### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.ransac_voting_gpu_layer.ransac_voting'

### ISSUE THREAD

**Issue by emilychen6160** [zju3dv/pvnet#136]
When we run the file "demo.py" with instruction "python3 tools/demo.py", there are some problem like ...
 "Traceback (most recent call last):
  File "tools/demo.py", line 7, in <module>
    from lib.ransac_voting_gpu_layer.ransac_voting_gpu import ransac_voting_layer_v3
  File "/media/prl-dl/NDDS/YZCHEN/pvnet/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 2, in <module>
    import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting
ModuleNotFoundError: No module named 'lib.ransac_voting_gpu_layer.ransac_voting'"
Hoping can help us to solve the problem, thank you.

**Comment by pengsida** [comment]
You need to compile the code.

**Comment by emilychen6160** [comment]
thanks!
