### ISSUE TITLE
paper question

### ISSUE THREAD

**Issue by ewwll** [zju3dv/pvnet#139]
I read your paper and have some problems. Is the correspondence between the camera internal parameters and the key points known? What if the camera's internal parameters are calibrated and the image will be distorted?

**Comment by pengsida** [comment]
1. The correspondences are known.
2. What do you mean by "What if the camera's internal parameters are calibrated and the image will be distorted?"

**Comment by ewwll** [comment]
I mean if the reprojection error of the camera calibration will affect the accuracy of the estimate?

**Comment by pengsida** [comment]
No.
