### ISSUE TITLE
The question about testing in LM-O

### ISSUE THREAD

**Issue by Mr2er0** [zju3dv/pvnet#142]
你好，这里读入了LM-O的pose信息为什么需要这一步的转化呢，occlusion_pose_to_blender_pose代表的是什么意思呢？是因为训练的时候就已经发生了转化吗？
[链接](https://github.com/zju3dv/pvnet/blob/48e5066668f7563434373bc909b842a7bd94b7b9/lib/utils/data_utils.py#L594)

**Comment by pengsida** [comment]
因为Linemod occlusion的object model坐标系和linemod的坐标系不一样。
