### ISSUE TITLE
How to find correspondence between 2d keypoints and 3d keypoints

### ISSUE THREAD

**Issue by hkd724** [zju3dv/pvnet#144]
你好，
          有幸拜读你的论文，但是对文中列举的2d-3d对应关系不甚了解。文中提到2d的keypoints可以用像素的向量投票决定，3d keypoints 可以由 farthest point sampling确定。但是这些2d、3d的keypoint好像没有联系，没有建立一对一的匹配呢？这个配对关系是可以根据cad模型直接得出还是需要用其他算法判断呢？
感谢！

**Comment by pengsida** [comment]
这个配对关系可以根据cad模型直接得出。

**Comment by Zephyr-One** [comment]
> 这个配对关系可以根据cad模型直接得出。

2D点是像素坐标系下的，我理解的3D坐标应该是物体在相机坐标系下的3D坐标，请问怎么获取呢？CAD模型是怎么和相机坐标系产生联系呢？
