### ISSUE TITLE
Question about symmetric objects

### ISSUE THREAD

**Issue by simoooooooon** [zju3dv/pvnet#145]
In your paper and the other papers, **glue** and **eggbox** are considered as symmetric objects in LINEMOD dataset. But I wonder where the symmetry of **glue** is (since the hat of  **glue** has the different symmetry axis with the body of  **glue**), and why **duck** isn't treated as a symmetric object (it seems to me that **duck** is symmetrical like **eggbox**.).

I'd appreciate it if you could answer it.

**Comment by pengsida** [comment]
1. glue and eggbox are symmetric along the axis.
2. duck is symmetric along the plane, so it is not treated as a symmetric object in the problem of object pose estimation.
