### ISSUE TITLE
Question: Training on one 3D Model generalized for the same model but with differenz sizes?

### ISSUE THREAD

**Issue by harezhh** [zju3dv/pvnet#146]
Hello,

I have a question. As I understood we have to build for the object of interest a 3D Model. In my project I would like to detect the pose of cardboard boxes. Imagine I would follow your tutorial and create a 3D Model of a box with specific size. 

Would the network then also detect boxes with other sizes as the 3D Model?

Thank you.

**Comment by pengsida** [comment]
Yes. But you need to change the scale of 3D keypoints when detecting the 3D model of other sizes.
