### ISSUE TITLE
关于训练以及数据的问题

### ISSUE THREAD

**Issue by OUVUO** [zju3dv/pvnet#147]
您好，我有一个关于数据的问题，在linemod数据集训练中会自动的有数据增强，然后这个增强是不是没有考虑R,T？只是单纯的将语义分割和向量进行了增强？如果我想在训练的loss中加入有关R,T的公式，那么R,T的ground truth怎么得到？
谢谢您？

**Comment by pengsida** [comment]
1. 这个增强没有考虑RT。
2. 代码里的dataset有读取RT。

**Comment by Y1996-wwj** [comment]
> 

您好，我想问下，作者应该没有在训练阶段就去生成预测的RT吧？

**Comment by pengsida** [comment]
没有。

**Comment by Y1996-wwj** [comment]
> 没有。

您好作者，请问如果我想在训练阶段就生成预测的RT，请问应该怎样做呢？您可以提供一个大体的思路吗？非常感谢您！，因为我想在训练阶段就通过一个loss函数去约束RT，但是我不太明白该如何在训练阶段生成RT。
