### ISSUE TITLE
Training image size?

### ISSUE THREAD

**Issue by MichaelOdum** [zju3dv/pvnet#15]
![Screenshot from 2019-04-22 19-47-17](https://user-images.githubusercontent.com/18298080/56499704-1e28a700-653a-11e9-82af-b9ca1c0952f8.png)
In your class LineModDatasetRealAug, I see you resized image size, but I confuse what is the training image size?

**Comment by pengsida** [comment]
See https://github.com/zju3dv/pvnet/blob/master/lib/datasets/linemod_dataset.py#L314
