### ISSUE TITLE
truncation linemod

### ISSUE THREAD

**Issue by OUVUO** [zju3dv/pvnet#151]
您好，请问truncation linemod数据集在哪下载。

**Comment by OUVUO** [comment]
之前的链接下载不了了，求大佬能分享一下，~~~~(>_<)~~~~，谢谢您了。

**Comment by OUVUO** [comment]
已经解决了，谢谢您

**Comment by OUVUO** [comment]
已经解决了，谢谢您

**Comment by QRayMoor** [comment]
请问如何测试truncation linemod数据集，训练指令是什么？
