### ISSUE TITLE
libgoogle-glog-dev

### ISSUE THREAD

**Issue by CodeKingWang** [zju3dv/pvnet#152]
我的系统是乌班图18.04，手动下载，然后sudo dpkg -i libgoogle-glog-dev_0.3.4-0.1_arm64.deb会出现：
dpkg: 处理软件包 libgoogle-glog-dev:arm64 (--install)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 libgoogle-glog-dev:arm64

**Comment by pengsida** [comment]
ubuntu18.04不能安装libgoogle-glog-dev_0.3.4-0.1。
如果不用uncertainty-pnp，可以不装libgoogle-glog-dev。需要修改build_extend_utils_cffi.py文件。

**Comment by CodeKingWang** [comment]
> ubuntu18.04不能安装libgoogle-glog-dev_0.3.4-0.1。 如果不用uncertainty-pnp，可以不装libgoogle-glog-dev。需要修改build_extend_utils_cffi.py文件。

您好，方便解答下怎么修改嘛？

**Comment by pengsida** [comment]
可能把文件里和ceres相关的文件移除就可以了。https://github.com/zju3dv/pvnet/blob/master/lib/utils/extend_utils/build_extend_utils_cffi.py#L6
或者你用另一个代码：https://github.com/zju3dv/clean-pvnet
