### ISSUE TITLE
可视化的loss图

### ISSUE THREAD

**Issue by OUVUO** [zju3dv/pvnet#153]
#91 大佬您好，在这个 #91 问题里您 提供的训练的loss图，在开源的代码里能直接调用，可视化出来吗？谢谢您。

**Comment by pengsida** [comment]
你可以看这个代码：https://github.com/zju3dv/clean-pvnet

**Comment by OUVUO** [comment]
嗯嗯，好的谢谢您，我去clean-pvnet看一下，在pvnet这个没有这个可视化的吗？

**Comment by OUVUO** [comment]
嗯嗯，谢谢您！
