### ISSUE TITLE
关于Truncation Linemod数据集

### ISSUE THREAD

**Issue by OUVUO** [zju3dv/pvnet#154]
您好，我对于Truncation Linemod数据集有一些问题想请教您，通过随机裁剪得到的截断数据集，它的图像尺寸发生了变化，那它的姿态信息标签是怎么得到的？

**Comment by pengsida** [comment]
他的姿态信息不会发生变化。

**Comment by OUVUO** [comment]
谢谢您的及时的解答，因为我看截断数据集里图片尺寸为256*256了和原图像640*480不同了，所以是不是检测出的物体2D点坐标也会变？因为姿态信息不变，物体3D关键点不变，那在图像上的投影坐标也不应该变啊，所以我有这个疑问，谢谢您的解答。

**Comment by OUVUO** [comment]
> 他的姿态信息不会发生变化。

谢谢您的及时的解答，因为我看截断数据集里图片尺寸为256256了和原图像640480不同了，所以是不是检测出的物体2D点坐标也会变？因为姿态信息不变，物体3D关键点不变，那在图像上的投影坐标也不应该变啊，所以我有这个疑问，谢谢您的解答。

**Comment by pengsida** [comment]
我们修改了相机内参，所以二维关键点坐标会变。

**Comment by OUVUO** [comment]
> 我们修改了相机内参，所以二维关键点坐标会变。

嗯嗯，谢谢您。
