### ISSUE TITLE
Can we estimate just the center location of object instead of 8 keypoints using RANSAC?

### ISSUE THREAD

**Issue by faheemullah** [zju3dv/pvnet#156]
Using the same approach, can we estimate just the center location of object as in PoseCNN using RANSAC? Is RANSAC-based voting or Hough voting is useful for center point estimation? Not sure how both works and how the voting process works, how it selects keypints or just center point?

**Comment by pengsida** [comment]
Yes. The estimated keypoints include the 2D projection of the object's 3D center location.
