### ISSUE TITLE
Custom keypoints annotations

### ISSUE THREAD

**Issue by IsRaTiAlv** [zju3dv/pvnet#157]
Hello, according to your paper, you used a custom set of key points instead of the bounding box cornets, right? Where I could find those annotations? Is it perhaps in the directory labels_occlusion? If so, what is the format of the data, since I couldn't find any relationship with the corresponding object. Thanks in advance.

**Comment by pengsida** [comment]
Read this code: https://github.com/zju3dv/clean-pvnet/blob/master/tools/handle_custom_dataset.py#L19
