### ISSUE TITLE
Question: in demo/cat  fps nums is 9, not 8 default, in cat_points_3d.txt

### ISSUE THREAD

**Issue by zkl99999** [zju3dv/pvnet#16]
https://github.com/zju3dv/pvnet/blob/1752c5004fff22b1d178199e8de9053e9e2af774/data/demo/cat_points_3d.txt#L9 

and the trained model you supply, the number fps is 9fps,????
but ,in your literature compute 8fps by deflault

**Comment by zkl99999** [comment]
when i run demo.py, change vote_num=9, in line 29,  error occur
RuntimeError: Error(s) in loading state_dict for Resnet18_8s:
        size mismatch for convraw.3.weight: copying a param of torch.Size([18, 32, 1, 1]) from checkpoint, where the shape is torch.Size([20, 32, 1, 1]) in current model.
        size mismatch for convraw.3.bias: copying a param of torch.Size([18]) from checkpoint, where the shape is torch.Size([20]) in current model.
Terminated

**Comment by zkl99999** [comment]
and the fps result ,fartherst  data domain different, 
in   pvnet/data/demo/cat_points_3d.txt   
2.178440988063812256e-02  -5.869993939995765686e-02   -4.146179929375648499e-02

in

**Comment by liuyuan-pal** [comment]
The default keypoints are 8 points sampled on the surface by FPS and the center of the object.

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/56732058-c636ae00-678e-11e9-8f9f-837d4609f074.png)
