### ISSUE TITLE
demo运行问题

### ISSUE THREAD

**Issue by plainzzj** [zju3dv/pvnet#160]
您好，冒昧打扰，新手复现，根据README一步一步实现，运行demo.py时遇到了一个问题，卡了好几天未解决：

from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: libceres.so.2: cannot open shared object file: No such file or directory

根据您的其他回答逐个排查：
已经设置好了 LD_LIDBRARY_PATH
![image](https://user-images.githubusercontent.com/93184749/184464178-7b693eb0-fdd9-4d7d-acd9-7849a21622a6.png)

lib/utils/extend_utils/lib下也有相关的文件
![image](https://user-images.githubusercontent.com/93184749/184464064-a568925e-c478-4b3e-b583-8d35347b3117.png)

GCC版本降到了5.5.0

十分感谢！

**Comment by pengsida** [comment]
如果是pycharm运行，需要设置pycharm的环境变量。
