### ISSUE TITLE
ImportError: libspqr.so.2.0.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sean6585** [zju3dv/pvnet#161]
I have successfully run `build_extend_utils_cffi.py`, the result as shown below:
![Screenshot from 2022-08-25 20-46-00](https://user-images.githubusercontent.com/59359578/186669686-106e6595-c699-430e-b68a-734514fb050c.png)

And also run `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/pvnet/lib/utils/extend_utils/lib` (I've modified the path), checked by runnung `echo $LD_LIBRARY_PATH`
![image](https://user-images.githubusercontent.com/59359578/186670274-0d4650c2-e2e5-4c5f-a2a7-13fdccd2374a.png)

But when I run `python tools/demo.py`, still got the error:
![image](https://user-images.githubusercontent.com/59359578/186670551-141ee9a1-c1e8-4bbd-a055-e73bfed92df7.png)

Here are files under lib folder:
![image](https://user-images.githubusercontent.com/59359578/186839380-5950703b-7948-4663-81dc-4af137b22173.png)

Could someone help me solve this ? Thank you!
ubuntu version: 18.04
gcc version: 7.5.0
cuda version: 10.2
pytorch version: 1.5

**Comment by sean6585** [comment]
According to #17
I tried this one https://github.com/zju3dv/pvnet/blob/master/build_ceres.sh
build ceres through cmake
and I got this error
![image](https://user-images.githubusercontent.com/59359578/187084521-1599e645-a07c-423b-aeb4-fd10db5f0271.png)

**Comment by pengsida** [comment]
We did not try the uncertainty-driven PnP on Ubuntu 18.04.
You can run the code without the uncertainty-driven PnP.

**Comment by sean6585** [comment]
I tried to rebuild by following instructions below and it works.
![image](https://user-images.githubusercontent.com/59359578/187200841-04397b48-fba5-4768-ad45-c6065d9abf52.png)

after this, run this command `python build_extend_utils_cffi.py`

**Comment by sean6585** [comment]
My pytorch version is 1.5.0, so this problem showed up:
![image](https://user-images.githubusercontent.com/59359578/187201537-129ff2b2-00e9-4fe6-91b3-0469d1ab47fe.png)

just change the 'gesv' to 'solve' in the python file
![image](https://user-images.githubusercontent.com/59359578/187202443-eee051a7-e333-476d-973a-65b69902f08f.png)

**Comment by sean6585** [comment]
> We did not try the uncertainty-driven PnP on Ubuntu 18.04. You can run the code without the uncertainty-driven PnP.

Thank you for replying! If I have any questions, I will open a new issue.
