### ISSUE TITLE
A little tip to author

### ISSUE THREAD

**Issue by sdu-huanhq** [zju3dv/pvnet#162]
Dear authors, 
    First thanks for opening up the source code. Recently, I'm try to run the code, but I miss a problem when I'm preparing the linemod data. For example, when I tried to prepared `cam` data and run `python run.py --type linemod cls_type cam` in cmd. But there was an error: `data/linemod/cam/test_occlusion.txt not found`.

 Since there is no `cam` data in the lm-o dataset, it is impossible to test on the lm-o dataset, so you do not need to run this command for the `cam` data.
   
The author can post this tip on github, which might help researchers with this problem.

---
简单来说，在数据集准备阶段，对于lm-o数据集中没有的数据，不需要运行`python run.py --type linemod cls_type cls`这行代码，因为这是为test准备的，而test是在lm-o数据集上进行的。以cam数据为例，lm中有，但lm-o中没有，所以你运行`python run.py --type linemod cls_type cam`肯定会报错。

**Comment by pengsida** [comment]
谢谢。
