### ISSUE TITLE
run data_utils.py error, libspqr.2.0.2 not found

### ISSUE THREAD

**Issue by sky7hate** [zju3dv/pvnet#17]
I found my libspqr in /usr/lib/x86_64-linux-gnu/ is 2.0.8.
so I met error when running data_utils.py as follow:
**Traceback (most recent call last):
  File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/jiaming/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: libspqr.so.2.0.2: cannot open shared object file: No such file or directory**
Could this be solved?

**Comment by liuyuan-pal** [comment]
The PVNet depends on the Ceres Solver for the solving uncertainty PnP problem.
You can follow the installation tutorial in http://ceres-solver.org/installation.html.

The following steps are essential for building a shared ceres library.
```Python
# - However, if you want to build Ceres as a *shared* library, you must
#   add the following PPA:
sudo add-apt-repository ppa:bzindovic/suitesparse-bugfix-1319687
sudo apt-get update
sudo apt-get install libsuitesparse-dev
```

**Comment by pengsida** [comment]
Reading README.md is a good habbit, and you will feel it.

![image](https://user-images.githubusercontent.com/11582122/56806200-cc479000-685d-11e9-80db-d2c55c22d72f.png)

**Comment by 571502680** [comment]
> I found my libspqr in /usr/lib/x86_64-linux-gnu/ is 2.0.8.
> so I met error when running data_utils.py as follow:
> Traceback (most recent call last):
> File "lib/utils/data_utils.py", line 18, in 
> from lib.utils.extend_utils.extend_utils import farthest_point_sampling
> File "/home/jiaming/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in 
> from lib.utils.extend_utils._extend_utils import lib, ffi
> ImportError: libspqr.so.2.0.2: cannot open shared object file: No such file or directory
> Could this be solved?

Do you have solved this error? i have the same error,

**Comment by pengsida** [comment]
sudo apt-get install libsuitesparse-dev

**Comment by sky7hate** [comment]
install libsuitesparse-dev cannot solve this problem, though I tried from the very beginning for several times.
I'm still trying to figure out.

**Comment by 571502680** [comment]
> install libsuitesparse-dev cannot solve this problem, though I tried from the very beginning for several times.
> I'm still trying to figure out.

I cannot solve it too

**Comment by pengsida** [comment]
Please run the following command and paste its output
`cd /usr/lib/x86_64-linux-gnu; ls | grep libspqr`

**Comment by 571502680** [comment]
> cd /usr/lib/x86_64-linux-gnu

its output:
libspqr.a
libspqr.so
libspqr.so.1.3.1
but i how to install libspqr.2.0.2?

**Comment by pengsida** [comment]
`sudo apt-get install libsuitesparse-dev=1:4.4.6-1` might help.

**Comment by pengsida** [comment]
I have updated README.md. Thanks for your correction.

**Comment by sky7hate** [comment]
> `sudo apt-get install libsuitesparse-dev=1:4.4.6-1` might help.

I met error below.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1:4.4.6-1' for 'libsuitesparse-dev' was not found

Could you tell me if you added some repository before install it, I cannot find a solution to install libspqr2.0.2 from google. And my libspqr in /usr/lib/x86_64-linux-gnu is libspqr2.0.8.

**Comment by sky7hate** [comment]
I found this problem may caused by my usage of ubuntu 18.04, which do not support libsuitesparse-dev 1:4.4.6-1 or any of its depends libs.
I will try with another system and tell you the result.
Thanks for help.

**Comment by pengsida** [comment]
> I found this problem may caused by my usage of ubuntu 18.04, which do not support libsuitesparse-dev 1:4.4.6-1 or any of its depends libs.
> I will try with another system and tell you the result.
> Thanks for help.

Thanks for your feedback.

**Comment by joy-yjl** [comment]
> > I found this problem may caused by my usage of ubuntu 18.04, which do not support libsuitesparse-dev 1:4.4.6-1 or any of its depends libs.
> > I will try with another system and tell you the result.
> > Thanks for help.
> 
> Thanks for your feedback.

so ubuntu 18.04 can not be use for this project？Is there any package that can replace libspqr.2.0.2?

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet/issues/39

**Comment by harkiratbehl** [comment]
I am still not able to use it on ubuntu 18.04 because of this error. So it is better to let this issue stay open.

**Comment by shuluoshu** [comment]
> I am still not able to use it on ubuntu 18.04 because of this error. So it is better to let this issue stay open.

I solved the problem by re-compiling the Ceres and got new libCeres.so, in this case, you do not need to rely on the specific libspqr.2.0.2.

**Comment by pengsida** [comment]
Could you tell me how to re-compile Ceres or just upload the libCeres.so

**Comment by shuluoshu** [comment]
> Could you tell me how to re-compile Ceres or just upload the libCeres.so

@pengsida , Just download the source code of Ceres and modify the CMakeList.txt by setting "build_shared_library" to True, and compile it with your own version of dependencies to generate new libceres.so. In this case, it does not rely on the specific suitesparse version any more. In other words, you can use any version of suitesparse/eigen/glog as you like to compile Ceres. 

Different systems have specific compiled libCeres.so, so it is meaningless to upload my  libCeres.so.

**Comment by pengsida** [comment]
Ok, thank you! I get it.

**Comment by pengsida** [comment]
I write a script to build ceres: https://github.com/zju3dv/pvnet/blob/master/build_ceres.sh
![image](https://user-images.githubusercontent.com/11582122/62942644-4d299800-be0b-11e9-895f-712ef30276a1.png)

**Comment by huygiang93** [comment]
> > I am still not able to use it on ubuntu 18.04 because of this error. So it is better to let this issue stay open.
> 
> I solved the problem by re-compiling the Ceres and got new libCeres.so, in this case, you do not need to rely on the specific libspqr.2.0.2.

can you instruct how to do this?

**Comment by pengsida** [comment]
You could learn how to run ceres code in your computer.
