### ISSUE TITLE
关于训练的物体泛化性的疑惑

### ISSUE THREAD

**Issue by pange1802703882** [zju3dv/pvnet#171]
彭博士你好，我在试验位姿估计网络过程中，发现在linmod数据集上，采用训练集和生成的渲染render去测试同一个场景下抽帧出来的测试集，效果比较好。在自己的数据集上也使用同一个场景下的训练测试集(训练测试集是录制了一长段视频然后抽帧形成的)，然后加上render渲染图效果也会比较好。但是用这个模型切换一个场景(或者说不用这段视频里面的帧，重新录制一段视频)测试，效果就不太好，请问这是什么原因呀，和训练的数据量有关系吗?

**Comment by pengsida** [comment]
背景对泛化能力会影响比较大。可以加一个检测器，将物体区域截取出来。
