### ISSUE TITLE
About LINEMOD dataset

### ISSUE THREAD

**Issue by F-jie** [zju3dv/pvnet#20]
thanks for your nice work! In LINEMOD dataset, there is a file called, for example, **ape_farthest.txt**, which include 15 3D points. what is it, is it the same with farthest4/12...?

**Comment by pengsida** [comment]
It is one of the keypoint settings used for the ablation study.

**Comment by F-jie** [comment]
Thanks for your quick reply! I have another question about #5, could i use the data in correspond ply file to generate **dense_pts.txt**? if couldn't, how can i generate it for my own CAD model.

**Comment by pengsida** [comment]
You can use a software, CloudCompare, to generate dense_pts.txt for your own CAD model.
`dense_pts.txt` is a point cloud with 6d data, including spatial position, rgb and normal.

**Comment by sky7hate** [comment]
> You could use a software, CloudCompare, to generate dense_pts.txt for your own CAD model.
> `dense_pts.txt` is a point cloud with 9d data, including spatial position, rgb and normal.

@pengsida I used pymesh to calculate normal and generate file with format of dense_pts.txt, but found that my generated dense_pts.txt for cat.ply (as an example) is quite different from yours. Is it right to use the .ply files in LINEMOD to generate dense_pts?

**Comment by pengsida** [comment]
Yes, I use ply files to generate dense_pts.
I never use pymesh. I used CloudCompare.
