### ISSUE TITLE
question: visulizaiotn.ipynb cannot open with jupyter notebook

### ISSUE THREAD

**Issue by zkl99999** [zju3dv/pvnet#21]
when open visualization.ipynb  show error
NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...",)

**Comment by pengsida** [comment]
I do not have the problem in my local environment.
nbviewer is an alternative: https://nbviewer.jupyter.org/github/zju3dv/pvnet/blob/master/visualization.ipynb

**Comment by zkl99999** [comment]
my anaconda error,,   thank you to supply this visualization notebook
