### ISSUE TITLE
which is the url to download LINEMOD_ORIG

### ISSUE THREAD

**Issue by detectRecog** [zju3dv/pvnet#22]
Hello, I cannot find the url to downlaod LINEMOD_ORIG. The url in the README.md redirects to a personal page. Some links seem like datasets:

`
Here you can find the databases for the ape, benchvise, bowl, can, cat, cup, driller, duck, glue, holepuncher, iron, lamp, phone, cam and eggbox. 
`

I wonder do these links represent LINEMOD_ORIG Dataset? I'm not familar with LINEMOD. Please help me

**Comment by pengsida** [comment]
The link you said is exactly the original LINEMOD.

![image](https://user-images.githubusercontent.com/11582122/57629375-49993180-75ce-11e9-89f5-ee09f25fd5d1.png)

**Comment by detectRecog** [comment]
Thank you, I create a script to download the LINEMOD_ORIG Dataset, it might help others if you can help provide these commands and clarify the way these files construct the LINEMOD_ORIG dataset.

`
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/ape.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/benchviseblue.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/bowl.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/can.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/cat.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/cup.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/driller.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/duck.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/glue.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/holepuncher.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/iron.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/lamp.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/phone.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/cam.zip'
wget 'http://campar.in.tum.de/personal/hinterst/index/downloads!09384230443!/eggbox.zip'
`

**Comment by pengsida** [comment]
As your suggestion, I provide a script modified from yours to automatically download the LINEMOD_ORIG dataset: https://github.com/zju3dv/pvnet/blob/master/tools/download_linemod_orig.sh
Thank you very much!
