### ISSUE TITLE
some questions about runing data_utils.py

### ISSUE THREAD

**Issue by ybyangjing** [zju3dv/pvnet#24]
Thank you very much for you sharing code.
This problem makes me unable to solve.when I run python lib/utils/data_utils.py.
![problem1](https://user-images.githubusercontent.com/18078935/58131005-81fec800-7beb-11e9-8f00-211f51da9125.png)
I search the source code and found the extend_utils.py file.
![Selection_001](https://user-images.githubusercontent.com/18078935/58131110-cd18db00-7beb-11e9-9c5c-f888738ebca3.png)
So I don't know why I am executing the code error.
Can anyone know this reason? Thank you.

**Comment by pengsida** [comment]
Which python version, python2 or 3

**Comment by ybyangjing** [comment]
@pengsida python2.7

**Comment by pengsida** [comment]
Please use python3.
