### ISSUE TITLE
problems about Compute FPS keypoints

### ISSUE THREAD

**Issue by LAX007** [zju3dv/pvnet#25]
When I run lib/utils/data_utils.py, I got this error:

Traceback (most recent call last):
  File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/lax/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: libceres.so.2: cannot open shared object file: No such file or directory

How may I solve it? Thanks.

**Comment by pengsida** [comment]
Follow the README
![image](https://user-images.githubusercontent.com/11582122/58418099-65660280-80b9-11e9-9189-8f1ee702d705.png)

**Comment by RiplleYang** [comment]
> Follow the README
> ![image](https://user-images.githubusercontent.com/11582122/58418099-65660280-80b9-11e9-9189-8f1ee702d705.png)
抱歉这么唐突，请问在clean-pvnet版本里面没有extend_utils该怎么解决这个问题呢
