### ISSUE TITLE
libceres.so.2

### ISSUE THREAD

**Issue by hillaric** [zju3dv/pvnet#26]
File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/liuguangyuan/pvnet-master/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: libceres.so.2: cannot open shared object file: No such file or directory

**Comment by pengsida** [comment]
See https://github.com/zju3dv/pvnet/issues/25

**Comment by AingLee** [comment]
@hillaric , have you solved your problems yet? now I am facing with this problem too even though I added the path.
