### ISSUE TITLE
data_utils.py

### ISSUE THREAD

**Issue by hillaric** [zju3dv/pvnet#27]
Traceback (most recent call last):
  File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/liuguangyuan/pvnet-master/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: /home/hillaric/pvnet-master/lib/utils/extend_utils/_extend_utils.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringEv

**Comment by pengsida** [comment]
I have no idea of your error.
Please list your system, python, cuda and gcc configurations.

**Comment by hillaric** [comment]
Ubuntu 16.04.4, python=3.6.7, cuda=9.0, pytorch=0.4.1 and gcc=4.9.3

**Comment by pengsida** [comment]
It seems missing libglog.so from https://abi-laboratory.pro/?view=compat_report&l=glog&v1=0.3.2&v2=0.3.3&obj=a0a41&kind=abi.
![image](https://user-images.githubusercontent.com/11582122/58474259-30bb7f00-817d-11e9-965f-503de00db228.png)

Please run `ls /usr/lib/x86_64-linux-gnu | grep libglog` and paste what it outputs.

**Comment by hillaric** [comment]
libglog.a
libglog.so
libglog.so.0
libglog.so.0.0.0

**Comment by pengsida** [comment]
It seems your libglog.so does not have `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()`.
Please run `cd /usr/lib/x86_64-linux-gnu; objdump -TC libglog.so | grep CheckOpMessageBuilder` and paste what it outputs.

**Comment by hillaric** [comment]
000000000000df30 g    DF .text	000000000000001d  Base        google::base::CheckOpMessageBuilder::ForVar2()
000000000000df50 g    DF .text	0000000000000158  Base        google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()
000000000000f0c0 g    DF .text	00000000000001df  Base        google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)
000000000000df10 g    DF .text	0000000000000012  Base        google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder()
000000000000f0c0 g    DF .text	00000000000001df  Base        google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)
000000000000df10 g    DF .text	0000000000000012  Base        google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder()

**Comment by pengsida** [comment]
Use gcc 5.4.0.
![image](https://user-images.githubusercontent.com/11582122/58478232-2488ef00-8188-11e9-935f-75e2b74476ea.png)

**Comment by pengsida** [comment]
https://github.com/ceres-solver/ceres-solver/issues/291

**Comment by hillaric** [comment]
Thank you, it works well!
