### ISSUE TITLE
nn.upsampling

### ISSUE THREAD

**Issue by hillaric** [zju3dv/pvnet#28]
UserWarning: nn.UpsamplingBilinear2d is deprecated. Use nn.functional.interpolate instead.

**Comment by hillaric** [comment]
Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
Segmentation fault (core dumped)

**Comment by hillaric** [comment]
so can I modifie the upsampling in the model_repository.py

**Comment by pengsida** [comment]
Yes

**Comment by hillaric** [comment]
what value should I take for the scale_factor(0.5 ?), and I think you can rewrite the network.

**Comment by hillaric** [comment]
I has tried, but the problem of Segmentation fault is not solved

**Comment by hillaric** [comment]
![image](https://user-images.githubusercontent.com/50513602/58505514-b52ef180-81bf-11e9-84a7-ef049dafb080.png)

**Comment by pengsida** [comment]
In pytorch v0.4.1, it is just a warning and won't cause errors.
For this case, I suppose that you might also cannot run other pytorch codes.

**Comment by hillaric** [comment]
And why there existes a segmentation fault ? I use gdb to debug, the problem is __gnu_cxx, but I do not know how to make it?

**Comment by pengsida** [comment]
It is a pytorch problem, and I don't know why.

**Comment by DHNicoles** [comment]
I also encountered the same problem and also used the GDB debugging tool. The error is located in a layer called _UP, which crashes when the forward function is executed.
![image](https://user-images.githubusercontent.com/13547926/58747807-e00c9480-84a2-11e9-980b-d40ef63c0e45.png)

[The system environment is centos7.2, the gcc version is 4.8.5, the python version is 3.6.8, and the torch version is 0.4.1.]

**Comment by pengsida** [comment]
The problem means you cannot run 'nn.upsampling()', which is exactly a pytorch problem.

**Comment by DHNicoles** [comment]
> I also encountered the same problem and also used the GDB debugging tool. The error is located in a layer called _UP, which crashes when the forward function is executed.
> ![image](https://user-images.githubusercontent.com/13547926/58747807-e00c9480-84a2-11e9-980b-d40ef63c0e45.png)
> 
> [The system environment is centos7.2, the gcc version is 4.8.5, the python version is 3.6.8, and the torch version is 0.4.1.]

Solved this problem: upgrade gcc version to 5.4.0.

**Comment by zeal-github** [comment]
@DHNicoles I encountered the same problem -- segmentation fault. And my GPU is RTX, so I have to use pytorch 1.x according to the author.  Can you give me more details about how did you solve this problem? My gcc version is 5.4.0.

**Comment by DHNicoles** [comment]
@zeal-github It's better to check again if you have a strict configuration according to the author's requirements.
