### ISSUE TITLE
Test RuntimeError

### ISSUE THREAD

**Issue by G-YY** [zju3dv/pvnet#29]
When I run python demo.py,I met the flowing error:
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411
My GPU is 2080ti,CUDA 10.0 
How can I slove the problem?Thank you.

**Comment by pengsida** [comment]
Have you followed the installation instruction?
And could you provide more detailed error message so that I can see which line incurs this error

**Comment by G-YY** [comment]
> Have you followed the installation instruction?
> And could you provide more detailed error message so that I can see which line incurs this error
Thank you for your reply. This is the detailed error:
![图片](https://user-images.githubusercontent.com/46116343/59106656-835d1e00-8969-11e9-96bf-b9b61f3b8cad.png)

**Comment by G-YY** [comment]
Thank you for your reply. This is the detailed error:
![图片](https://user-images.githubusercontent.com/46116343/59107003-49d8e280-896a-11e9-9d4f-fd534e6d0cad.png)

**Comment by pengsida** [comment]
https://github.com/pytorch/pytorch/issues/13038

It seems like a RTX GPU problem.

**Comment by G-YY** [comment]
I want to estimate multi-object pose, how to make the label? @pengsida

**Comment by pengsida** [comment]
Our code does not enable multi-object training.
You could do this by preparing the semantic labels, unit vectors, mask for each object.

**Comment by pengsida** [comment]
@G-YY How did you solve this problem
