### ISSUE TITLE
About cat_points_3d.txt

### ISSUE THREAD

**Issue by DHNicoles** [zju3dv/pvnet#30]
Hello, thanks for your nice work! In the demo, the parameters in cat_points_3d.txt are used to help estimate the pose. However, I found that it is different from the farthest*txts.  If used to demo other categories, how can I get it (eg. can_point_3d.txt)?

**Comment by pengsida** [comment]
The cat_points_3d.txt is actually the `FPS 8` points of the object, and you can find it under object directories as the name `farthest.txt`.
The reason they are different is that FPS algorithm randomly selects 8 points such that these points are farthest to each other.

**Comment by DHNicoles** [comment]
I understand. But comparing the two files, I found that the scales between the values are very different. So, I am not clear what you mean by "randomly selects", is there any other conversion?

demo/cat_points_3d.txt
> 2.178440988063812256e-02 -5.869993939995765686e-02 -4.146179929375648499e-02
-2.093566954135894775e-02 6.558419764041900635e-02 3.955494984984397888e-02
2.779895067214965820e-02 2.978627011179924011e-02 -4.446335881948471069e-02
1.394690014421939850e-03 -5.708838999271392822e-02 3.459186106920242310e-02
1.266971044242382050e-02 1.578414067625999451e-02 7.163164764642715454e-02
-3.255600109696388245e-02 -3.509996086359024048e-02 -4.010977968573570251e-02
-2.941701933741569519e-02 2.281758934259414673e-02 -3.967477008700370789e-02
2.389688976109027863e-02 4.313550889492034912e-02 3.052332065999507904e-02
-2.315007150173187256e-04 2.015497535467147827e-03 1.328250020742416382e-02

LINEMOD/cat/farthest.txt

> 0.021784409880638123 -0.05869993939995766 -0.041461799293756485
> -0.020935669541358948 0.065584197640419 0.03955494984984398
> 0.027798950672149658 0.02978627011179924 -0.04446335881948471
> 0.0013946900144219398 -0.05708838999271393 0.03459186106920242
> 0.01266971044242382 0.015784140676259995 0.07163164764642715
> -0.03255600109696388 -0.03509996086359024 -0.0401097796857357
> -0.029417019337415695 0.022817589342594147 -0.03967477008700371
> 0.02389688976109028 0.04313550889492035 0.03052332065999508

>

**Comment by pengsida** [comment]
2.178440988063812256e-02 is approximately 0.021784409880638123.
Learn about FPS algorithm and you will know what I said.

**Comment by DHNicoles** [comment]
Thanks so much!

**Comment by lwcode** [comment]
why are there 9 lines data in demo/cat_points_3d.txt，but only 8 lines data in LINEMOD/cat/farthest.txt？

**Comment by pengsida** [comment]
9 points: 1 center point and 8 farthest points.

**Comment by lwcode** [comment]
Thanks so much！
