### ISSUE TITLE
Train and test problem 

### ISSUE THREAD

**Issue by pureYioYi** [zju3dv/pvnet#32]
When I came to step Train:
python tools/train_linemod.py --cfg_file configs/linemod_train.json --linemod_cls cat

The Error:
Traceback (most recent call last):
  File "tools/train_linemod.py", line 72, in <module>
    os.path.join(cfg.REC_DIR,train_cfg['model_name']+'.log'))
  File "/home/yx/Projects/PVNet/lib/utils/net_utils.py", line 177, in __init__
    self.writer = SummaryWriter(log_dir=rec_dir)
  File "/usr/local/lib/python3.5/dist-packages/tensorboardX/writer.py", line 254, in __init__
    self._get_file_writer()
  File "/usr/local/lib/python3.5/dist-packages/tensorboardX/writer.py", line 310, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'

Anyone could tell me how to solve with it? Thanks!

**Comment by pengsida** [comment]
The tensorboardX version does not match.
Simply removing `log_dir` in `self.writer = SummaryWriter(log_dir=rec_dir)` is ok.

**Comment by pureYioYi** [comment]
I tried it, but failed with :

Traceback (most recent call last):
  File "tools/train_linemod.py", line 19, in <module>
    from lib.utils.net_utils import AverageMeter, Recorder, smooth_l1_loss, \
  File "/home/yx/Projects/PVNet/lib/utils/net_utils.py", line 178
    self.writer = SummaryWriter(rec_dir)
                                       ^
TabError: inconsistent use of tabs and spaces in indentation

What about  the right version of  tensorboardX?

Meanwhile I tried this project with python 3.5.2, should I run with python 3.6.7?  Thank you!

**Comment by zhangxiaodi** [comment]
> When I came to step Train:
> python tools/train_linemod.py --cfg_file configs/linemod_train.json --linemod_cls cat
> 
> The Error:
> Traceback (most recent call last):
> File "tools/train_linemod.py", line 72, in 
> os.path.join(cfg.REC_DIR,train_cfg['model_name']+'.log'))
> File "/home/yx/Projects/PVNet/lib/utils/net_utils.py", line 177, in **init**
> self.writer = SummaryWriter(log_dir=rec_dir)
> File "/usr/local/lib/python3.5/dist-packages/tensorboardX/writer.py", line 254, in **init**
> self._get_file_writer()
> File "/usr/local/lib/python3.5/dist-packages/tensorboardX/writer.py", line 310, in _get_file_writer
> self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
> TypeError: **init**() got an unexpected keyword argument 'log_dir'
> 
> Anyone could tell me how to solve with it? Thanks!

hi brother! can you give me a pretrained model link from google or baidu cloud?
