### ISSUE TITLE
How to Get 3D Points

### ISSUE THREAD

**Issue by hz-ants** [zju3dv/pvnet#33]
In demo, coordinates in cat_bb8_3d.txt are preset by Blender, and coordinates in cat_points_3d.txt are obtained by estimating_voting_distribution_with_mean?

**Comment by pengsida** [comment]
cat_bb8_3d.txt is the 3D bounding box of the object.
cat_points_3d.txt is the `FPS 8 point` of the object.

**Comment by XinjieInformatik** [comment]
> cat_bb8_3d.txt is the 3D bounding box of the object.
> cat_points_3d.txt is the FPS 8 point of the object.

in object coordinate(world coordinate)?

**Comment by pengsida** [comment]
Yes.
