### ISSUE TITLE
some problem about debug

### ISSUE THREAD

**Issue by robotSunGina** [zju3dv/pvnet#36]
hello, thanks for your method. when run the demo.py, there are some problems ,like 
Traceback (most recent call last):
  File "/home/robot/Downloads/pvnet-master/tools/demo.py", line 8, in <module>
    from lib.ransac_voting_gpu_layer.ransac_voting_gpu import ransac_voting_layer_v3
  File "/home/robot/Downloads/pvnet-master/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 2, in <module>
    import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting
ImportError: /home/robot/Downloads/pvnet-master/lib/ransac_voting_gpu_layer/ransac_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs
can you tell me reasons , thanks for your time.

**Comment by pengsida** [comment]
Have you compiled the ransac voting layer

**Comment by robotSunGina** [comment]
I compiled the ransac voting layer,but this problem still exists

**Comment by robotSunGina** [comment]
I compiled the ransac voting layer,but this problem still exists

**Comment by pengsida** [comment]
It is possible that the compiling environment and runtime environment are not the same. You could have a check.
