### ISSUE TITLE
Why is uncertainty_pnp not used as default?

### ISSUE THREAD

**Issue by mrlooi** [zju3dv/pvnet#37]
Hey, great work on the paper and the repo. 

Curious to know why uncertainty pnp is not used by default, when it seems to be one of the main contributions of the paper

**Comment by pengsida** [comment]
Since our method is faster without uncertainty-driven PnP

**Comment by mrlooi** [comment]
Right, so uncertainty-PnP's accuracy-speed tradeoff is not worth using?

**Comment by pengsida** [comment]
The uncertainty-PnP is worth using. I just prefer a faster method.
