### ISSUE TITLE
Can this project run on CentOS linux?

### ISSUE THREAD

**Issue by fred2019-dev** [zju3dv/pvnet#38]
The required versions of libglog/libsuitesparse/libatlas can't be found in the CentOS's yum list. I used available versions of libglog/libsuitesparse/libatlas in the yum list, and build up my own libceres.so, but it can't be linked to the _extend_utils.so.  
Has anyone managed to get this project running on CentOS? I really need your help, thanks very much !!!

**Comment by pengsida** [comment]
Docker might help.

**Comment by fred2019-dev** [comment]
> Docker might help.

Thanks very much, i will take a try then.
