### ISSUE TITLE
未找到“libgoogle-glog-dev”的“0.3.4-0.1”版本

### ISSUE THREAD

**Issue by ZJsonJun** [zju3dv/pvnet#39]

**Comment by pengsida** [comment]
Maybe your system is not ubuntu 16.04.
You could manually install it by downloading `http://launchpadlibrarian.net/216637511/libgoogle-glog-dev_0.3.4-0.1_arm64.deb` and `sudo dpkg -i libgoogle-glog-dev_0.3.4-0.1_arm64.deb`.

**Comment by ZJsonJun** [comment]
thank you ,now i switch to 16.04 for easy
