### ISSUE TITLE
How to read depth png?

### ISSUE THREAD

**Issue by chenynCV** [zju3dv/pvnet#41]
How to read depth png?
I can't read the PNG depth with cv2.IMREAD_UNCHANGED

**Comment by pengsida** [comment]
```
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

img = Image.open('0_depth.png')
img = np.array(img)
plt.imshow(img)
plt.show()
```

**Comment by chenynCV** [comment]
I try code above. 
But `img` is binary mask, not depth.
How can I get depth?

**Comment by pengsida** [comment]
Yes, our rendering code gives a binary mask, not depth.
You could get the depth by modifying our rendering code.

**Comment by chenynCV** [comment]
Where is your main rendering code?  Can you show me the URL?  Thank you.

**Comment by pengsida** [comment]
If you don't know my rendering code, where do you get the depth data.
My rendering code: https://github.com/zju3dv/pvnet-rendering

**Comment by chenynCV** [comment]
I just download the pre processed dataset. 
I will have a look.  Thank you.
