### ISSUE TITLE
Occluded-LineMod dataset train/validation split

### ISSUE THREAD

**Issue by SelvamArul** [zju3dv/pvnet#42]
Hi,

I have a question regarding the train/validation split used for Occluded-LineMod dataset from [onedrive link](https://onedrive.live.com/?authkey=%21ALO%5FLTl%2DMqpH%5F94&cid=613A42359D6163D6&id=613A42359D6163D6%21144&parId=613A42359D6163D6%21123&action=locate). I am trying to understand the train/validation split that should be used. This [ICCV_15 challenge](https://hci.iwr.uni-heidelberg.de/vislearn/iccv2015-occlusion-challenge/) page says "You can use anything as training data except the test sequences provided in the dataset.". The dataset contains XXX_val.txt file for each object. Does this mean we can use all the images in the dataset for training and avoid the specific occurrences of the objects as per those  XXX_val.txt file?

Sorry, this question is not really about PVnet but very general to the Occluded-LineMod.

**Comment by pengsida** [comment]
You can use all the images except images in XXX_val.txt.

**Comment by SelvamArul** [comment]
Okay, now it is clear. Thanks for the reply.
