### ISSUE TITLE
Coordinate system convention of the ground truth poses

### ISSUE THREAD

**Issue by SelvamArul** [zju3dv/pvnet#43]
Hi,
One more question related to original LineMOD. The ground truth poses in Occluded-LineMOD dataset follows the OpenGL Coordinate system convention (camera viewing direction is the negative Z-axis)  as mention in the section 2.2 of [this](https://hci.iwr.uni-heidelberg.de/vislearn/HTML/projects/scene_understanding/OcclusionDataset_ReadMe.pdf) document. But I am not sure of the coordinate system convention used in the original LineMOD dataset. For example one of the transformation file like looks like 
        `-13.0792` 
       `-7.83575`
        `104.177` 
 The values are in **centimetres**. 
so, that's ~1 meters along the _positive_ _z_-axis.
This make me think that the poses are annotated with [OpenCV](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html) 
coordinate system convention. But my rendering pipeline is not working correctly if I follow this assumption.  Any idea how the ground truth poses in original LineMOD dataset is defined?
Sorry again that this issue is also not about the PVNet but rather a general question.

**Comment by pengsida** [comment]
Original Linemod and Occluded Linemod both have object models under their directories.
You could use CloudCompare to compare their models and manually align or compute the rotation between two dataset models. The resulting transformation is what you want.

**Comment by SelvamArul** [comment]
Thanks a lot for your reply. [This](https://github.com/cvlab-epfl/segmentation-driven-pose/issues/5) suggested me to use a different version of LINEMOD and it works.
