### ISSUE TITLE
about camera intrinsic parameters

### ISSUE THREAD

**Issue by ZJsonJun** [zju3dv/pvnet#47]
why do you use different intrinsic matrix K of camera in rendered data compared to real data?
Is there any special purpose here?

**Comment by zhangxiaodi** [comment]
hi, can you download the pretrained model from those link?  i want to test author's model, but i can't download it. Maybe it has been failed.

**Comment by ZJsonJun** [comment]
the data is in onedrive but you are in china, and you need a vpn

**Comment by pengsida** [comment]
Because they have different camera intrinsic matrices.
We take an image using a camera, and every camera has its own intrinsic matrices.

**Comment by ZJsonJun** [comment]
actually, I mean that why not you use the same K in rendering data as real data?
why dou you choose a new K in rendering?

**Comment by pengsida** [comment]
Because I do not know how to change the camera matrix in blender.

**Comment by ZJsonJun** [comment]
in others words, the K in rendering is the default setting of blender?

**Comment by pengsida** [comment]
Yes.
If you want to keep the camera matrix of images the same, you could use the opengl to render images.
