### ISSUE TITLE
occulution dataset can't Inaccurate projection

### ISSUE THREAD

**Issue by liuzehao** [zju3dv/pvnet#48]
I want to use this K * R | T * POINTS formula to calculate the projection of an object. The result shows that the projection of an object can not be displayed correctly. Has the author dealt with the model or the R | T matrix?
![Screenshot from 2019-07-11 14-21-23](https://user-images.githubusercontent.com/13258781/61027362-8a53d200-a3e8-11e9-8ac3-0d410f5b6e5a.png)
![Screenshot from 2019-07-11 14-21-47](https://user-images.githubusercontent.com/13258781/61027363-8aec6880-a3e8-11e9-8fa5-98e3beec7739.png)
![Screenshot from 2019-07-11 14-22-16](https://user-images.githubusercontent.com/13258781/61027364-8b84ff00-a3e8-11e9-9607-5c92320c9cbd.png)
![Screenshot from 2019-07-11 14-22-39](https://user-images.githubusercontent.com/13258781/61027365-8c1d9580-a3e8-11e9-8871-f0562b42b51f.png)
![Screenshot from 2019-07-11 14-23-00](https://user-images.githubusercontent.com/13258781/61027367-8c1d9580-a3e8-11e9-8722-51a8678b3961.png)
![Screenshot from 2019-07-11 14-23-22](https://user-images.githubusercontent.com/13258781/61027368-8d4ec280-a3e8-11e9-8492-364117f75e73.png)

**Comment by pengsida** [comment]
You need to transform the cad model.
