### ISSUE TITLE
Could you share the pre-trained model and the Truncation Dataset in other way?

### ISSUE THREAD

**Issue by RobbyHuang** [zju3dv/pvnet#50]
Could you share the pre-trained model and the Truncation Dataset in other way, like the BaiduNetdisk?There are something wrong to visit the onedrive. Thank you so much

**Comment by pengsida** [comment]
Sorry, my uploading speed for the BaiduNetdisk is so slow.
If you are able to visit google, you only need to add the onedrive to your GFWList.
