### ISSUE TITLE
Clarification on Training the Voting Layers

### ISSUE THREAD

**Issue by bsvineethiitg** [zju3dv/pvnet#52]
Thank you for the new ideas, great work! 

I am a little unclear how you are training the voting layer looking at the code. Could you please clarify?

1. Are you only training the vectors within the segmentation mask and not outside of it? Are you explicitly enforcing zero vectors outside the segmask (per class per keypoint type)? (I had this question because your plots on the paper look pretty neat with vectors appearing only within the mask).

2. Do you weight the gradients differently based on the distance from the target keypoint when training?

3. Could you please explain the voting scheme when you say "farthestxx" in your code?

Thank you!

**Comment by bsvineethiitg** [comment]
One additional query. Glad if you can clarify.

4. If your scene doesn't have any instance of a specific class, how do you train the voting vectors there? Do you train them to be zeros across the whole position or do you only train them to be zeros only within the bounding box regions of the other existing instance class regions? 

Looking forward to your reply.
Thanks!

**Comment by pengsida** [comment]
1. I trained the vectors within the segmentation mask and ignored the the rest of vectors.
2. I did not weight the gradients.
3. "farthestxx" has the same voting scheme with other types of keypoint. It indicates the keypoint sampled by "farthest point sampling algorithm".
4. If the scene doesn't have any instance, we just simply ignore the whole image, as described in 1.

**Comment by bsvineethiitg** [comment]
Thank you very much for your response. 

Just a quick follow up. 

My wording might have been confusing. In 4 I did not mean the case where an image doesn't have any class instance.

I meant the following -- Say a scene has a cat but does not have a dog. Then do you train the keypoint vectors for ONLY the "cat" class channels and do not pass any gradient signal to suppress the outputs for the "dog" class? Or do you train to suppress the non-existent classes?

Does your visualization of vectors in the paper only consider the predicted vectors in the correct class channel? [Because if the wrong classes are not suppressed, superimposing all predicted vectors within a mask gives a bunch of crowded vectors across all the classes].

Thank you again for the clarification!

**Comment by pengsida** [comment]
I trained the keypoint vectors for only the "car" class channels. I did not suppress the non-existent classes.
We only considered the predicted vectors in the correct class channel.
