### ISSUE TITLE
Question about world coordinates

### ISSUE THREAD

**Issue by Sunweijun333** [zju3dv/pvnet#53]
I would like to ask if the world coordinate system in the LINEMOD data set is built on the object model, and the coordinate transformation relationship between the world coordinate system and the object remains relatively unchanged.

**Comment by pengsida** [comment]
What we care about is not the world coordinate but the transformation between the object coordinate and the camera coordinate.

**Comment by Sunweijun333** [comment]
In predicting the pose, the pnp algorithm is used, but the 3d coordinate points of the key points input therein are known, not predicted, that is, for each picture, the 3d coordinate points are the same. If the world coordinate system is not built on the model, then how to achieve the key point coordinates of the picture is the same?

**Comment by pengsida** [comment]
The keypoint coordinate is at the object frame, not the world frame.

**Comment by pengsida** [comment]
Yes, the world coordinate system is built on the model.

**Comment by Sunweijun333** [comment]
Thank you for your reply！
