### ISSUE TITLE
about voting and uncertainty pnp

### ISSUE THREAD

**Issue by XsyamojiX** [zju3dv/pvnet#54]
I have some questions about voting and uncertainty pnp.

I think that the implement (ransac_voting_layer_v3) is theoretically different from the paper.
In the implement, the mean value m_k is not calculated and set to the most confident point.
Additionally, I cannot understand a part of the implement.
What are ATa and ATb in ransac_voting_layer_v3?

It is about uncertainty pnp.
I want to try demo using uncertainty pnp.
How do I use uncertainty pnp in demo?
I tried to use estimate_voting_distribution_with_mean, but it takes 100 msec per 1 frame on RTX 2070.

Thank you.

**Comment by pengsida** [comment]
The implementation is different from what we describe in the paper.
`ATA` and `ATb` are used to compute the mean value, the intersection of the sampled vectors.

**Comment by XsyamojiX** [comment]
Is there the implementation described in the paper in the git project?

**Comment by liuyuan-pal** [comment]
The open resource code is an improved version to find the keypoints from directions.
The function ransac_vote_layer_v3 actually has done the following things.
1. Generate hypotheses and let pixels vote for hypotheses.
2. Find out the hypothesis with the largest amount of votes and mark these pixels voting for this hypothesis as inliers.
3. 
![image](https://user-images.githubusercontent.com/23974453/62116178-4ddf0c00-b2ec-11e9-81f4-5647b5703189.png)

**Comment by XsyamojiX** [comment]
I understand the implementation.
Thank you.

**Comment by shanniruo** [comment]
@liuyuan-pal @pengsida @XsyamojiX  how does the solution be inferred?thanks

![22](https://user-images.githubusercontent.com/41144161/112925529-97789d80-9144-11eb-8d45-4124fd3938fd.png)

**Comment by pengsida** [comment]
https://textbooks.math.gatech.edu/ila/least-squares.html
