### ISSUE TITLE
 libspqr.so.2.0.2: cannot open shared object file

### ISSUE THREAD

**Issue by harkiratbehl** [zju3dv/pvnet#55]
Traceback (most recent call last):
  File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/harkirat/msr_rendering/azureml/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: libspqr.so.2.0.2: cannot open shared object file: No such file or directory

**Comment by pengsida** [comment]
How about https://github.com/zju3dv/pvnet/issues/39

**Comment by deerlululu** [comment]
Traceback (most recent call last):
  File "tools/demo.py", line 8, in <module>
    from lib.ransac_voting_gpu_layer.ransac_voting_gpu import ransac_voting_layer_v3
  File "/home/net663/PVNet/pvnet-master/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 2, in <module>
    import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting
ImportError: /home/net663/PVNet/pvnet-master/lib/ransac_voting_gpu_layer/ransac_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6detail20DynamicCUDAInterface20unchecked_set_deviceE

**Comment by shuluoshu** [comment]
> Traceback (most recent call last):
> File "lib/utils/data_utils.py", line 18, in 
> from lib.utils.extend_utils.extend_utils import farthest_point_sampling
> File "/home/harkirat/msr_rendering/azureml/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in 
> from lib.utils.extend_utils._extend_utils import lib, ffi
> ImportError: libspqr.so.2.0.2: cannot open shared object file: No such file or directory

reinstall ceres by yourself and copy the libceres.so to "lib", in this case, you don't need the specific libspqr.so.2.0.2 at all. I tried that on centos and it works.

**Comment by pengsida** [comment]
I write a script to build ceres: https://github.com/zju3dv/pvnet/blob/master/build_ceres.sh

**Comment by pengsida** [comment]
If no problem, I will close this issue.

**Comment by marufff92** [comment]
I still get the same error even after running your script. Do you have a idea how to solve the problem without switching to ubuntu 16.04.?

**Comment by pengsida** [comment]
If you cannot install libsuitesparse-dev=1:4.4.6-1, please install libsuitesparse, run build_ceres.sh and move ceres/ceres-solver/build/lib/libceres.so* to lib/utils/extend_utils/lib.

**Comment by marmas92** [comment]
I already did that but get the same error. After build_ceres.sh I only get the following files in  ceres/ceres-solver/build/lib/
![image](https://user-images.githubusercontent.com/51153981/64149512-5ca66a80-ce26-11e9-9aaf-3d9008c54f1c.png)

**Comment by pengsida** [comment]
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/pvnet/lib/utils/extend_utils/lib`
