### ISSUE TITLE
reproducing results

### ISSUE THREAD

**Issue by kk1153** [zju3dv/pvnet#57]
I get below results for LINEMOD dataset with the models released by you. Do you know why cat trained model is not working? Is it working for you? Also, results are slightly worse than what's reported in the paper.  I am evaluating using uncertainity_pnp on test data.

'200':
  ADD:
    ape: 49.24
    benchvise: 99.81
    cam: 86.57
    can: 95.28
    cat: 0.0
    driller: 96.43
    duck: 57.65
    eggbox: 99.34
    glue: 95.56
    holepuncher: 82.49
    iron: 98.77
    lamp: 99.42
    phone: 92.51
  Reprojection_metric:
    ape: 96.67
    benchvise: 99.71
    cam: 98.82
    can: 99.31
    cat: 0.0
    driller: 96.73
    duck: 97.28
    eggbox: 98.69
    glue: 97.01
    holepuncher: 99.81
    iron: 98.88
    lamp: 98.18
    phone: 99.23

**Comment by pengsida** [comment]
I don't know the cat problem.
The voting result is based on ransac, so our method will gives different result every time, sometime higher and sometimes lower.

**Comment by kk1153** [comment]
Can you check if the cat model is actually working on your machine. It works for the demo for me but not the test set. 

And just as a suggestion, you can fix the randomness by fixing a random seed.

**Comment by pengsida** [comment]
In our environment, it works fine.
You can see the demo result deserves a pass, so the cat accuracy should not be zero.

**Comment by trevor-taeyeop** [comment]
@kk1153  Do you solve the problem?? 
I think I have similar problem in my environment.
If you solved, Could you share the reason.

> val epoch 128 step 128 seg 0.00302757  ver 0.00633340  precision 0.94480604  recall 0.94429278  projection_error 0.97804391  add 0.40818363  cm 0.45309381 
> epoch 128 val cost 105.93580412864685 s
> 
> occ_val epoch 128 step 128 seg 0.00766029  ver 0.27710328  precision 0.83434725  recall 0.60907692  projection_error 0.00252738  add 0.00000000  cm 0.00000000 
> epoch 128 occ_val cost 105.84267544746399 s
>
