### ISSUE TITLE
export LD_LIDBRARY_PATH=$LD_LIDBRARY_PATH:/path/to/bb8-voter/lib/utils/extend_utils/lib

### ISSUE THREAD

**Issue by SimonTHa** [zju3dv/pvnet#61]
in training part：
Is it
`export LD_LIDBRARY_PATH=$LD_LIDBRARY_PATH:/path/to/bb8-voter/lib/utils/extend_utils/lib`
or
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/pvnet/lib/utils/extend_utils/lib`

I don‘t know what the “bb8-voter” is。。

**Comment by pengsida** [comment]
`bb8-voter` is `pvnet`

**Comment by SimonTHa** [comment]
> `bb8-voter` is `pvnet`

thanks
