### ISSUE TITLE
Running Real-Time Demo

### ISSUE THREAD

**Issue by mattygrs** [zju3dv/pvnet#63]
Hello,

I was wondering how I would be able to run the demo seen in the 'Real-time demo' video seen [here](https://zju3dv.github.io/pvnet/). 

Thank you!

**Comment by pengsida** [comment]
We additionaly write a program that reads camera frames and saves the network output.
Then we convert these outputs into a video.

**Comment by mattygrs** [comment]
Hello, thank you for your response.

I just wanted to clarify: would the network output be the results of using the network on images received from the camera? Where would these outputs be saved?

Thank you again!

**Comment by pengsida** [comment]
1. Yes.
2. Where these outputs being saved is determined by you.

**Comment by mattygrs** [comment]
If I was to make my own program for real-time detection, would I be able to use this with a library such as OpenCV to use my camera frames with the network and overlay the output? And which script/piece of code in the project should be run to input my frames into the network?

**Comment by pengsida** [comment]
We do not upload the real-time demo code.
You could input your camera frames to our single-image demo code.
