### ISSUE TITLE
demo problem and image synthesis problem

### ISSUE THREAD

**Issue by JiangDing1995** [zju3dv/pvnet#65]
Thank you for your great work! But i meet two problems here:
1.When i run demo ,actually it works,no problem,but i notice the file"cat_pose.npy", so how can i find the same file of other objects,such"can_pose.npy"?Or where the file comes from?because i want to try other objects as well......
2.I see before training,we need to add the synthetic images,but when i run "python run.py --type rendering",it failed .I have set blender-2.79a well and have installed OpenEXR1.3.2.
Here is the problem:
python run.py --type rendering
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 11, in run_rendering
    from blender.render_utils import Renderer, YCBRenderer
  File "/home/robeon/PV-NET/pvnet-rendering-master/blender/render_utils.py", line 9, in <module>
    import OpenEXR
ImportError: /home/robeon/anaconda3/envs/python36/lib/python3.6/site-packages/OpenEXR.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7Iex_2_27BaseExcE

Hope for your answer,thanks a lot!

**Comment by pengsida** [comment]
1. cat_pose.npy is the ground truth for showing the ground truth bounding box.
2. Please google how to install OpenEXR.

**Comment by JiangDing1995** [comment]
ok, i see,thank you .And i still want to make sure that where to find xx_pose.npy of other objects? Are these in LINEMOD?

**Comment by pengsida** [comment]
It is generated using the ground truth "*.trat" and "*.rot" in orig linemod.
Note, the object coordinate in orig linemod is different from that of linemod, so you need to transform the ground truth of orig linemod to linemod.

**Comment by JiangDing1995** [comment]
ok，i'll have a try.

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet/issues/56

**Comment by JiangDing1995** [comment]
So does that mean i should change the "read_data()" in demo as #56 did?  
I see that "cat_points_3d.txt" contains FPS 8 points and the center ,but in #33 you said "cat_points_3d.txt is the FPS 8 point of the object".  So is the central point necessary?
thank you very much.
