### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by SimonTHa** [zju3dv/pvnet#66]
'''
testing occluded linemod ...
/.../pvnet-master/lib/utils/evaluation_utils.py:140: RuntimeWarning: invalid value encountered in arccos
  angular_distance = np.rad2deg(np.arccos((trace - 1.) / 2.))
Traceback (most recent call last):
  File "tools/train_linemod.py", line 358, in <module>
    train_net()
  File "tools/train_linemod.py", line 290, in train_net
    val(net, occ_test_loader, begin_epoch, prefix, use_motion=motion_model)
  File "tools/train_linemod.py", line 205, in val
    corner_pred=eval_net(seg_pred,vertex_pred).cpu().detach().numpy()
 File "/pvnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "tools/train_linemod.py", line 106, in forward
    return ransac_voting_layer_v3(mask,vertex_pred,128,inlier_thresh=0.99,max_num=100)
  File "./lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 594, in ransac_voting_layer_v3
    all_win_pts=torch.matmul(b_inv(ATA),torch.unsqueeze(ATb,2)) # [vn,2,1]
  File "./lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 511, in b_inv
    b_inv, _ = torch.gesv(eye, b_mat)
RuntimeError: gesv: For batch 7: U(1,1) is zero, singular U.
'''

**Comment by pengsida** [comment]
It has trouble in testing occluded linemod.
So it works fine on linemod?

**Comment by SimonTHa** [comment]
> It has trouble in testing occluded linemod.
> So it works fine on linemod?

yes

**Comment by pengsida** [comment]
Have you checked if the data of occluded linemod is right?
It seems that the prediction `mask` and `vertex_pred` is totally wrong, so we cannot compute the keypoint using least linear squares.

**Comment by SimonTHa** [comment]
好的，我再下载一下这个数据集，

**Comment by SimonTHa** [comment]
我又试了一次，还是会在相同的地方报错，这数据集就是按照给的连接下的[捂脸]，

**Comment by pengsida** [comment]
你torch的版本是多少。
测试linemod的结果是多少

**Comment by SimonTHa** [comment]
```
>>> torch.__version__
'1.0.1.post2'
>>> torch.version.cuda
'10.0.130'



testing normal linemod ...
val epoch 200 step 200 seg 0.00296773  ver 0.00413631  precision 0.93449301  recall 0.95625013  projection_error 0.98702595  add 0.48103792  cm 0.83133733 
epoch 200 val cost 85.36675786972046 s
```

**Comment by pengsida** [comment]
看上去挺正常的。
要不要换成0.4.1试试。
pytorch 1.0.1有bug，跑dilated convolution会特别慢，而且不知道有没有其他问题。

**Comment by SimonTHa** [comment]
好的，非常感谢。
