### ISSUE TITLE
ImportError: libceres.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yanzhou-li** [zju3dv/pvnet#67]
Thank you so much for sharing! now I have a problem.
when I run the code "lib/utils/data_utils.py",it will be reported the error:"ImportError: libceres.so.1: cannot open shared object file: No such file or directory."

As follows:
`Traceback (most recent call last):
  File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/media/cobot/5C8B2D882D247B56/li_pythorch_project/pvnet-master/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: libceres.so.1: cannot open shared object file: No such file or directory`

the " libceres.so.1*" has been  moved to "lib/utils/extend_utils/lib",but it can't work.
when I do "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/pvnet/lib/utils/extend_utils/lib" in my pycharm,it also doesn't work.
can you tell me what's that means, and how to get it works,thanks.

**Comment by pengsida** [comment]
You need to revise `/path/to/pvnet/lib/utils/extend_utils/lib` according to your real path.

**Comment by yanzhou-li** [comment]
> You need to revise `/path/to/pvnet/lib/utils/extend_utils/lib` according to your real path.

thank you!
