### ISSUE TITLE
ImportError: /home/mlz/pvnet/lib/ransac_voting_gpu_layer/ransac_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by ameliamlz** [zju3dv/pvnet#68]

**Comment by pengsida** [comment]
Use gcc 5.4.
Ensure your pytorch cuda is the same with your system cuda.

**Comment by ameliamlz** [comment]
I installed gcc5.4.0 and used pytorch1.1.0,then problem was solved.

**Comment by ameliamlz** [comment]
there is a new problem.
FileNotFoundError: [Errno 2] No such file or directory: '/home/mlz/projects/pvnet/data/LINEMOD/renders/cat/0_RT.pkl'

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet#synthesize-images-for-each-object
or simply not to use the rendering data.

**Comment by kroglice** [comment]
> https://github.com/zju3dv/pvnet#synthesize-images-for-each-object
> or simply not to use the rendering data.

Hello,

How can we disable rendering data? is there any simple config that can be used? or its needed to change some code?
