### ISSUE TITLE
Do you train the model for one obj per time? When test?

### ISSUE THREAD

**Issue by zeal-github** [zju3dv/pvnet#69]
Hi, I have a little question after roughly reading the code.
1. When train on LINEMOD,  the script provided in this repo train one object(one sequence) in LINEMODE one time. Do we use the trained network to continue train on another object? Or we trained one network for each object?

2. When you test on LINEMOD-occlusion, do you use one network to estimate all 8 objects in LINEMOD-occlusion, or 8 different network each for one object?

3. For YCB, since multiple objects are contained in one scene, so do you randomly select one object in a selected scene for one iter? 

A fantastic job~ I will appreciate if you give me a reply.

**Comment by pengsida** [comment]
1. We separately train a network for each object.
2. We use 8 different networks for testing on occluded linemod.
3. We had trained multiple classes on YCB. It requires a bigger network and is time consuming.

**Comment by zeal-github** [comment]
@pengsida Thanks for your reply.
So, the network used on YCB is not the network used in LINEMOD? Do you release the network model in this repo? 
I want to further confirm, given a scene image in YCB which contains multiple(e.g. 4) objects, we send it to the network to generate 4 predict key point set. Do you compute losses on these 4 key point sets and sum them up to do backpropagation?

**Comment by pengsida** [comment]
1. We do not release the pretrained model on YCB.
2. Yes, we sum up the losses.

**Comment by zeal-github** [comment]
For the first question, I am not asking for the pretrained model. I just want to make sure that whether the network architecture on ycb is the same as on LINEMOD(a modified resnet18 which is mentioned in the paper).
多谢兄dei

**Comment by pengsida** [comment]
We trained two models, resnet18 for each object and resnet101 for all objects.

**Comment by zeal-github** [comment]
I see. So I think the results on ycb reported in the paper is trained on resnet101. But the network architecture seems not contained in the code(only resnet18,34,50). Can you append the network architecture on this code? That will be kind.

**Comment by pengsida** [comment]
The results on ycb reported in the paper is trained on resnet18 for each object.
You just need to modify `ver_dim` and `seg_dim` in the network, so the network is almost the same.
Maybe I took resnet50 wrongly as resnet101. It is long time ago, and we did not adopt the mult-object version.

**Comment by zeal-github** [comment]
Thanks a lot, fantastic job.
