### ISSUE TITLE
What's the different between LINEMOD and LINEMOD_ORIG?

### ISSUE THREAD

**Issue by zeal-github** [zju3dv/pvnet#70]
I notice that the ground truth pose you use is actually the pose from LINEMOD_ORIG, but the image is from LINEMOD( singleshot6d version). I want to know why.

**Comment by pengsida** [comment]
we first downloaded LINEMOD at the very beginning and wrote code to read the data, but we found that it does not provide ground truth pose, so we additionally downloaded LINEMOD_ORIG.

**Comment by zeal-github** [comment]
I see. But it's weird that the 3D model in LINEMOD and LINEMOD_ORIG are different. I visualize them in meshlab, and find that they have 180 degree difference along Y axis.  Also, the model in  LINEMOD(singleshot6d) use length unit m, but ORIG use unit mm. It's weird.
