### ISSUE TITLE
pink cat 

### ISSUE THREAD

**Issue by jaehwan-pi** [zju3dv/pvnet#72]
Hello, Thank you for sharing nice work.
I'd like to reproduce your object tracking work by using the pink cat model like yours.
Is that pink cat commercial product?
If so, can I get any information where to buy that model?
Your answer will be really appreciated.
Thank you.

**Comment by pengsida** [comment]
I bought it from 3d print shop at taobao.

**Comment by jaehwan-pi** [comment]
thank you for your answer.
Does it mean that you requested to produce a model with your customized CAD file?
I thought the pink cat might be an commercial product with massive amount of production.
Is there any way to buy the same model like yours?

**Comment by pengsida** [comment]
I told the taobao shop to print a real model using the linemod 3d model.

**Comment by pengsida** [comment]
I don't know where to buy a model either.

**Comment by jaehwan-pi** [comment]
Thank you! Now I understood clearly.
