### ISSUE TITLE
About inference time on Occluded-LINEMOD and feature mapping for synthetic data

### ISSUE THREAD

**Issue by alen0216056** [zju3dv/pvnet#73]
Hello, I have a few questions after reading the issues:

1. You separately trained the network for each object, so the total inference time for multiple objects on Occluded-LINEMOD will be longer than the running time provided in the paper?
2. You compare your result with Oberweger[30] which used synthetic data and combined with feature mapping, do you also apply the feature mapping or directly use the rendered data?

Thank you for sharing a great job!

[30] M. Oberweger, M. Rad, and V. Lepetit. Making deep heatmaps robust to partial occlusions for 3d object pose estimation. In ECCV, 2018.

**Comment by pengsida** [comment]
1. The running time in our paper is for each object separately.
2. We directly used the rendered data.
