### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.utils.extend_utils._extend_utils'

### ISSUE THREAD

**Issue by blackriver65** [zju3dv/pvnet#74]
Traceback (most recent call last):
  File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/B/lxj/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ModuleNotFoundError: No module named 'lib.utils.extend_utils._extend_utils'

what should I do with this error?

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/64231286-c0618e00-cf21-11e9-906d-e04b93d59f0b.png)
