### ISSUE TITLE
Several errors occur in compute FPS keypoints step.

### ISSUE THREAD

**Issue by YuiTH** [zju3dv/pvnet#76]
Hi.
I have several problems when excuting lib/utils/data_utils.py

```
Exception has occurred: TypeError
__init__() got an unexpected keyword argument 'has_ro_set'
  File "/root/Code/pvnet/lib/utils/extend_utils/extend_utils.py", line 248, in <module>
    image_db = LineModImageDB('duck', has_ro_set=False, has_ra_set=False, has_plane_set=False, has_render_set=False,has_ms_set=False,has_fuse_set=False)
```
I search the whole project and I didn't found anything about this "has_ro_set" .So I delete has_ro_set ,has_ra_set ,has_plane_set and has_ms_set on this line.
Then this occured.
```
Exception has occurred: AttributeError
type object 'VotingType' has no attribute 'Extreme'
  File "/root/Code/pvnet/lib/utils/extend_utils/extend_utils.py", line 251, in <module>
    vote_type=VotingType.Extreme, augment=False)
```
I read the definition of VotingType and I found nothing about this Extreme things.
Could you give me some help about it? Or could I just skip this step.

Thank you.

_BTW: It seems that you use some link between libceres.so and libceres.so.1 etc. which I'm not sure what kind of link it is. But when I use git clone(through ssh) to download the repo to my machine, the link is broken. It tooks me serveal minutes to locate this problem .Maybe you want to mention it in README._

**Comment by pengsida** [comment]
`python lib/utils/data_utils.py`, not `python lib/utils/extend_utils/extend_utils.py`.

**Comment by YuiTH** [comment]
My fault. VS Code redirect me to extend_utils.py after my first error in data_utils.py. Now it's work fine. 
Just a little proposal, you could delete these out of date code for better readability.
Thank you for your time.

**Comment by pengsida** [comment]
Thanks for your suggestion. I will upload a cleaner code if the pami version of our paper is accepted.

**Comment by pengsida** [comment]
Thank you.

**Comment by pengsida** [comment]
@YuiTH We released a clean version of PVNet: https://github.com/zju3dv/clean-pvnet

**Comment by YuiTH** [comment]
> @YuiTH We released a clean version of PVNet: https://github.com/zju3dv/clean-pvnet

Thanks! A much cleaner work, helps me a lot.
