### ISSUE TITLE
does Training LINEMOD use "has_fuse" ? 

### ISSUE THREAD

**Issue by shuluoshu** [zju3dv/pvnet#77]
Hi, @pengsida , I want to know when you train a separate network for each object? do you use the "has_fuse=True" ? , or, do you just use the single rendered img, i.e., one rendered image only has one object.

**Comment by pengsida** [comment]
Yes, I used `has_fuse=True`.

**Comment by shuluoshu** [comment]
> Yes, I used `has_fuse=True`.

Thanks, one more question, in LINEMOD dataset,  you use both the fused dataset and the single rendered dataset, am I right? 
If I already got the single img from a certain view, i just combine it with a background image, is that Ok ?   I am confused about your " PoseTransformer ", Why need this ?

**Comment by pengsida** [comment]
1. You are right.
2. That is ok.
3. linemod's 3d models are different from those of orig linemod. PoseTransformer is used for getting correct 6d poses of linemod by transforming orig linemod's object coordinate frame to linemod's.
