### ISSUE TITLE
how to train like pretrained models? 

### ISSUE THREAD

**Issue by trevor-taeyeop** [zju3dv/pvnet#78]
Hi, pengsida

Thank you for sharing this great work!
I have a simple question about pretrained models. 

**There is some difference between pretrained model for demo ("cat_199.pth") and my own training model.** I think the difference is the making the synthetic data parts (pvnet-rendering).

> **[cat_pretrained(demo)_199]** 
> **val** epoch 200 step 200 seg 0.00221293 ver 0.00179207 precision 0.95590049 recall 0.95489734 projection_error 0.99700599 add 0.78343313 cm 0.98303393 epoch 200 val cost 121.78796076774597 s 
> **occ_val** epoch 200 step 200 seg 0.00420556 ver 0.02362387 precision 0.85987866 recall 0.78237575 projection_error 0.63016007 add 0.19123842 cm 0.18871104 epoch 200 occ_val cost 139.08751440048218 s
> 
> 
> **[cat_my_own_train_199]**
> **val** epoch 200 step 200 seg 0.00263701 ver 0.00421255 precision 0.94197798 recall 0.95716393 projection_error 0.98003992 add 0.50299401 cm 0.78942116 epoch 200 val cost 241.18241786956787 s 
> **occ_val** epoch 200 step 200 seg 0.00740673 ver 0.09852491 precision 0.88890141 recall 0.61555624 projection_error 0.33024431 add 0.05139006 cm 0.03959562 epoch 200 occ_val cost 259.331654548645 s 

Did I do something wrong?

Thanks.

**Comment by pengsida** [comment]
What's your pytorch version?
Why is your model's testing time much longer than that of the pretrained model?

**Comment by trevor-taeyeop** [comment]
- my torch version is 0.4.1

- When I test today again in the same environment, the testing time is similar. the reason testing time wass different is I think I did other works at the same times.  


> **[cat_my_own_train_199]**
> **val** epoch 200 step 200 seg 0.00263701 ver 0.00421255 precision 0.94197798 recall 0.95716393 projection_error 0.97904192 add 0.49001996 cm 0.79540918 epoch 200 val cost 116.80365562438965 s 
> **occ_val** epoch 200 step 200 seg 0.00740673 ver 0.09852491 precision 0.88890141 recall 0.61555624 projection_error 0.32771693 add 0.05812974 cm 0.04043808 epoch 200 occ_val cost 131.3461833000183 s
> 
> **[cat_pretrained(demo)_199]**
> **val** epoch 200 step 200 seg 0.00221293 ver 0.00179207 precision 0.95590049 recall 0.95489734 projection_error 0.99600798 add 0.77844311 cm 0.98203593 epoch 200 val cost 117.7701370716095 s 
> **occ_val** epoch 200 step 200 seg 0.00420556 ver 0.02362387 precision 0.85987866 recall 0.78237575 projection_error 0.63100253 add 0.18955350 cm 0.19292334 epoch 200 occ_val cost 127.38100290298462 s

**Comment by pengsida** [comment]
Sorry, I don't know what causes this problem.
Someone else has re-trained my model and got similar results.

**Comment by pengsida** [comment]
What is your rendering image's number?

**Comment by trevor-taeyeop** [comment]
- I use **10000 images from blender rendering** and **10000 images from fusion** (same to example)
- Some one did similar results means similar to pretrained demo result??

**Comment by pengsida** [comment]
Yes. We also trained twice previously and got similar results.

**Comment by trevor-taeyeop** [comment]
Thank you for your reply. I'll try again and ask you a question.

**Comment by trevor-taeyeop** [comment]
I found something that the results could change.
**I change the 'train_batch_size' 32 to 16** 
Due to limit of GPU power I used the two difference GPU(TITAN X PASCAL, TITAN X) for training.
Do you think this change also influence the results?

**Comment by pengsida** [comment]
Yes, this might influence the result.

**Comment by mentian** [comment]
> I found something that the results could change.
> **I change the 'train_batch_size' 32 to 16**
> Due to limit of GPU power I used the two difference GPU(TITAN X PASCAL, TITAN X) for training.
> Do you think this change also influence the results?

Could you please let me know how long it takes to train one epoch (about 20000 images) with 2 GPUs?

**Comment by pengsida** [comment]
About 5 minutes.

**Comment by sandy-ssdut** [comment]
> About 5 minutes.

How many GPUs did you use in parallel for training? 
Do you mind to tell us which kind of GPU you use？

**Comment by pengsida** [comment]
4 GPUs.
I used Titan XP.
