### ISSUE TITLE
src/nearest_neighborhood.cu.o Not found

### ISSUE THREAD

**Issue by banana16314** [zju3dv/pvnet#79]
Hi, Peng. when i run  python build_extend_utils_cffi.py, i got an error. 
src/nearest_neighborhood.cu.o: No such file or directory.
Thanks!

**Comment by pengsida** [comment]
Please list detailed error messages.

**Comment by banana16314** [comment]
there is problem with nvcc in my computer. i have solved it. Thanks

**Comment by futurev** [comment]
I have the same problem, could you share your solutions how you solved the problem? 

> there is problem with nvcc in my computer. i have solved it. Thanks

**Comment by jakobamb** [comment]
In case anyone has the same problem: In my case, i set --compiler-bindir to the wrong path when calling nvcc. So this error probably just appears when nvcc can't find (the correct) gcc executable.

Make sure you are using gcc-5
