### ISSUE TITLE
Did you train your model on a signle GTX 1080Ti card?

### ISSUE THREAD

**Issue by YuiTH** [zju3dv/pvnet#80]
Thank you for your time.
I notice that you use GTX 1080Ti during test time, and have a great performence. But when I try to train it on a signle RTX 2080Ti card, I had a CUDA out of memory error.  Did I do anything wrong or you trained it on multiple card?

**Comment by pengsida** [comment]
I trained it on multiple cards.
Reducing batch size will solve this problem.
