### ISSUE TITLE
how could the model produce multiple object 6d poses in one RGB image contanined several objects? I have read the #69

### ISSUE THREAD

**Issue by banana16314** [zju3dv/pvnet#81]
is there a general model for different objects in one RGB image?

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet/issues/69

**Comment by pengsida** [comment]
Do you have any questions about https://github.com/zju3dv/pvnet/issues/69

**Comment by banana16314** [comment]
Hi, dude.
1. do you train one network for one object class, e.g. cat category, or just for one object in the image? 

2. how do you select the object, e.g. a cat in your paper, among several objects in a single image? as there are a duck, a car... in your cat example
3. would you like to share your pretrained model on YCB if we wanna get one model which could make inference of multiple objects in a single image? 
Thanks!

**Comment by pengsida** [comment]
1. We trained one network for one object.
2. We use semantic segmentation.
3. Pretrained models on YCB also estimate only one object for each image. The pretrained models work on 3d models we haved adjusted, and the code used to adjust code is dirty, so we did not release the pretrained models.

**Comment by banana16314** [comment]
Thanks for your excellent work! It inspired me.
i find two multiple object pose estimation. 
1st: https://github.com/cvlab-epfl/segmentation-driven-pose
2nd: https://github.com/btekin/singleshot6Dpose
in case that someone needs it.
