### ISSUE TITLE
ImportError: libspqr.so.2.0.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GraceJary** [zju3dv/pvnet#84]
I have  already downloaded LineMod dataset ,and link it to the data folder .However, when I try to run 'python lib/utils/data_utils.py', it occured such error: 
Traceback (most recent call last):
  File "lib/utils/data_utils.py", line 19, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/media/srt/resource/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: libspqr.so.2.0.2: cannot open shared object file: No such file or directory

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/65491719-33877000-dee2-11e9-8db4-530a63b96edf.png)

**Comment by GraceJary** [comment]
Okay,it solved. Thank you very much.
![Screenshot from 2019-09-24 15-51-43](https://user-images.githubusercontent.com/34366402/65492289-3f276680-dee3-11e9-9657-036cb7a91573.png)
