### ISSUE TITLE
Trouble with demo.py

### ISSUE THREAD

**Issue by GraceJary** [zju3dv/pvnet#86]
enviroment:
python=3.6
torch =1.1.0
torchvision=0.3.0

When I run 'python demo.py', there occured such error:
Traceback (most recent call last):
  File "tools/demo.py", line 8, in <module>
    from lib.ransac_voting_gpu_layer.ransac_voting_gpu import ransac_voting_layer_v3
  File "/media/srt/resource/pvnet/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 2, in <module>
    import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting
ImportError: /media/srt/resource/pvnet/lib/ransac_voting_gpu_layer/ransac_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6detail20DynamicCUDAInterface10set_deviceE
![1569332128866](https://user-images.githubusercontent.com/34366402/65516350-757cda00-df13-11e9-8778-d80da935bf15.png)

**Comment by pengsida** [comment]
Ensure your torch cuda is the same as your system cuda

**Comment by GraceJary** [comment]
I install pytorch with 'conda install pytorch torchvision cudatoolkit=10.0 -c pytorch' .
Cuda version is 10.0.
![1569334179890](https://user-images.githubusercontent.com/34366402/65519133-1077b300-df18-11e9-8216-aac5c079eaa4.png)

**Comment by pengsida** [comment]
Run `python -c "import torch; print(torch.version.cuda)"` to see the torch cuda.

**Comment by GraceJary** [comment]
I checked the version of both pytorch and cuda.
![1569377595527](https://user-images.githubusercontent.com/34366402/65563748-32efe780-df7d-11e9-96a8-b1a08d369546.png)

**Comment by pengsida** [comment]
It seems weired.
This error happens when your compiled cuda version is inconsistent with pytorch cuda.
Are you sure that the nvcc used to compile ransac is 10.0.130.
You need to `export CUDA_HOME=/usr/local/cuda-10` before compilation.
If you recompile the code, you also need to delete the build directory under ransac code.

**Comment by GraceJary** [comment]
Thank you very much.I solved that problem follow your advice.
The results of demo are shown below.
I'm confused about the blue line.
![Screenshot from 2019-09-25 15-17-13](https://user-images.githubusercontent.com/34366402/65578027-9c84eb80-dfa7-11e9-8e02-e676f071bcff.png)

**Comment by pengsida** [comment]
You didn't correctly load the pretrained model.

**Comment by GraceJary** [comment]
You are right. I didn't load the cat_199.pth.
Now the result of demo looks well.
![1569398500784](https://user-images.githubusercontent.com/34366402/65581494-220b9a00-dfae-11e9-9281-08729537b9a0.png)
Besides,I tried to train the net by `python tools/train_linemod.py --cfg_file configs/linemod_train.json --linemod_cls cat
`


```python
Traceback (most recent call last):
  File "tools/train_linemod.py", line 358, in <module>
    train_net()
  File "tools/train_linemod.py", line 312, in train_net
    has_render_set=True)
  File "/media/srt/resource/Project/pvnet/lib/utils/data_utils.py", line 200, in __init__
    self.render_set=self.collect_render_set_info(self.render_pkl,self.render_dir)
  File "/media/srt/resource/Project/pvnet/lib/utils/data_utils.py", line 251, in collect_render_set_info
    data['RT']=read_pickle(os.path.join(self.linemod_dir,render_dir,'{}_RT.pkl'.format(k)))['RT']
  File "/media/srt/resource/Project/pvnet/lib/utils/base_utils.py", line 17, in read_pickle
    with open(pkl_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/srt/resource/Project/pvnet/data/LINEMOD/renders/cat/0_RT.pkl'

```

How can I get teh data *_RT.pkl ? Can I get it by `class PrinterModelDB(object)` in data_utils.py ?
Thank you very much~

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/65584198-19699280-dfb3-11e9-917d-1c0e908deea0.png)

**Comment by GraceJary** [comment]
Okay,thank you very much.
