### ISSUE TITLE
what is procedure to train on a custom object ?

### ISSUE THREAD

**Issue by jediofgever** [zju3dv/pvnet#89]

**Comment by pengsida** [comment]
I do not provide instructions for training on a custom object.
You could do this as follows:
1. Define farthest keypoints for your object as we do.
2. Generate training data including images, masks and their corresponding 6d poses.
3. Write a dataset reading images and 6d poses, and use 6d poses and keypoints to online generate vertex map for vector-field training.

**Comment by GraceJary** [comment]
我尝试使用pvnet-rendering中的渲染方法生成合成图像数据集,请问其中给出的相机内参,blender内参,以及world_to_camera_pose 是通用的吗? 在使用blender渲染图像的时候,world_to_camera_pose 是不是并不需要使用呢?

**Comment by GraceJary** [comment]
在获取数据集位姿的函数中,读取training_set中每一张训练图像对应的旋转rot(idx).rot和tra(idx).tra是物体在相机坐标系下的转换关系,还是相机在世界坐标系中的转换关系呢?这个部分我有点疑惑,非常感谢您的答疑解惑.

**Comment by pengsida** [comment]
1. world_to_camera_pose没有用到。
2. blender内参是渲染图片的相机内参。
3. 物体在相机坐标系下的转换关系。

**Comment by jediofgever** [comment]
Thanks for the reply , 
What exactly do you means mask ? , is it like the one used for instance segmentation ?

**Comment by pengsida** [comment]
Yes.

**Comment by jediofgever** [comment]
is there a script to generate "vertex map" from 6dof pose and keypoints?

**Comment by pengsida** [comment]
We generate it online at https://github.com/zju3dv/pvnet/blob/master/lib/datasets/linemod_dataset.py#L53

**Comment by jediofgever** [comment]
I see.., I have created a dataset with NVIDIA's  NDDS, not sure if you are familiar with, but do you have any insight about how can PVNET be trained on NDDS

**Comment by pengsida** [comment]
The problem is the same to training the network on a custom dataset.
