### ISSUE TITLE
关于torch.gesv()

### ISSUE THREAD

**Issue by Sunweijun333** [zju3dv/pvnet#90]
我现在在一块ARM板子上配置，运行demo.py 会爆出错误:RuntimeError: gesv: MAGMA library not found in compilation. Please rebuild with MAGMA.我在想有没有一种方法是不需要用到这个反转方法的？

**Comment by pengsida** [comment]
pytorch 1.1可以直接做矩阵的inverse，之前用gesv是因为pytorch 0.4.1没有矩阵batch inverse。

**Comment by Sunweijun333** [comment]
@pengsida 但是我目前由于条件需要，只能是0.4.1这样子，然后在板子上，装东西很不方便，我现在在编译尝试安装MAGMA，有点难受。。

**Comment by Sunweijun333** [comment]
为什么换成了torch1.0.1 还是会提示：RuntimeError: inverse: MAGMA library not found in compilation. Please rebuild with MAGMA.

**Comment by Sunweijun333** [comment]
改成这样：
``def b_inv(b_mat):
    '''
    code from
    https://stackoverflow.com/questions/46595157/how-to-apply-the-torch-inverse-function-of-pytorch-to-every-sample-in-the-batc
    :param b_mat:
    :return:
    '''
    #eye = b_mat.new_ones(b_mat.size(-1)).diag().expand_as(b_mat)
    b_inv = torch.inverse(b_mat)
    return b_inv

**Comment by pengsida** [comment]
建议换成torch 1.1, torch 1.0.1里的dilated convolution有bug。

**Comment by Sunweijun333** [comment]
我在终端里都可以：`>>> x = torch.rand(2,4,4)
>>> y = torch.inverse(x)
>>> print y
tensor([[[-18.8102,  16.9920,  -6.4309,   2.8340],
         [ -1.0638,   1.4286,  -2.1296,   1.2884],
         [ -3.3141,   3.8749,  -0.4524,  -0.8959],
         [ 10.9548, -10.2224,   4.9112,  -1.3140]],

        [[  4.2667, -13.2512,  -1.1034,   1.4513],
         [ -2.2366,   7.9790,  -0.2454,   0.3645],
         [  3.0325,  -3.1407,   1.0197,  -2.4379],
         [ -4.7344,  10.7087,   1.7366,  -0.0611]]])
`

**Comment by Sunweijun333** [comment]
我在终端里都可以
>>> x = torch.rand(2,4,4)
>>> y = torch.inverse(x)
>>> print y
tensor([[[-18.8102,  16.9920,  -6.4309,   2.8340],
         [ -1.0638,   1.4286,  -2.1296,   1.2884],
         [ -3.3141,   3.8749,  -0.4524,  -0.8959],
         [ 10.9548, -10.2224,   4.9112,  -1.3140]],

        [[  4.2667, -13.2512,  -1.1034,   1.4513],
         [ -2.2366,   7.9790,  -0.2454,   0.3645],
         [  3.0325,  -3.1407,   1.0197,  -2.4379],
         [ -4.7344,  10.7087,   1.7366,  -0.0611]]])

**Comment by Sunweijun333** [comment]
我测试了，ransac_voting_gpu.py   里的ransac_voting_layer_v3()
`       print(ATA.shape)
        result = torch.inverse(ATA)`
这样也会报错，其中ATA的shape是（9,2,2），我在终端测试都可以，很奇怪
`>>> x = torch.rand(9,2,2)
>>> y = torch.inverse(x)
>>> print y
tensor([[[ -6.0771,   6.0812],
         [  3.0592,  -2.0544]],

        [[  1.2782,  -0.0941],
         [ -0.5356,   1.4324]],

        [[  2.9087,  -3.2235],
         [ -0.9603,   2.7087]],

        [[-19.5225,  18.5913],
         [ 11.5627,  -9.8646]],

        [[  3.7211,  -4.2703],
         [ -3.5193,   6.4472]],

        [[ -1.4959,   2.7785],
         [  3.0106,  -1.9827]],

        [[ -7.6105,   5.5831],
         [  6.5239,  -3.6861]],

        [[ -2.9642,   2.7104],
         [  1.9298,  -0.5363]],

        [[-47.7656,  49.3446],
         [ 48.5136, -49.0527]]])
>>> 
`

**Comment by pengsida** [comment]
报什么错误？

**Comment by Sunweijun333** [comment]
RuntimeError: inverse: MAGMA library not found in compilation. Please rebuild with MAGMA.

**Comment by pengsida** [comment]
说明arm上需要MAGMA。

**Comment by Sunweijun333** [comment]
我编译了很长时间了，看看能不能行吧

**Comment by Sunweijun333** [comment]
最终通过源码编译MAGMA解决，现在可以运行在ARM板子上了，谢谢你
