### ISSUE TITLE
add path

### ISSUE THREAD

**Issue by AingLee** [zju3dv/pvnet#93]
@pengsida , I am sorry for raising this issue again, but I really cannot figure it out. the problem is that when I run this "python3 lib/utils/data_utils.py", I get the error output as following even I have already done this "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lee/Desktop/Research_Code/pvnet/lib/utils/extend_utils/lib". Have I done something wrong?, or something else have to be run? Thank you.

  File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/lee/Desktop/Research_Code/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: No module named 'lib.utils.extend_utils._extend_utils'

**Comment by pengsida** [comment]
You need compile `extend_utils` first.

**Comment by AingLee** [comment]
You means compiling "extend_utils" by running this "python3 build_extend_utils_cffi.py"? and I get the output
nvcc fatal   : Path to libdevice library not specified
generating ./_extend_utils.c
(already up-to-date)
the current directory is '/home/lee/Desktop/Research_Code/pvnet/lib/utils/extend_utils'
running build_ext
building '_extend_utils' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c _extend_utils.c -o ./_extend_utils.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 ./_extend_utils.o src/mesh_rasterization.cpp.o src/farthest_point_sampling.cpp.o src/uncertainty_pnp.cpp.o src/nearest_neighborhood.cu.o ./lib/libceres.so ./lib/libglog.so /usr/local/cuda-10.1/lib64/libcudart.so -lstdc++ -o ./_extend_utils.cpython-35m-x86_64-linux-gnu.so
x86_64-linux-gnu-gcc: error: src/nearest_neighborhood.cu.o: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 207, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lee/.local/lib/python3.5/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 557, in build_extension
    target_lang=language)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 209, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_extend_utils_cffi.py", line 39, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/lee/.local/lib/python3.5/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/lee/.local/lib/python3.5/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/lee/.local/lib/python3.5/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/lee/.local/lib/python3.5/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by pengsida** [comment]
`nvcc fatal : Path to libdevice library not specified`
There is a problem in your environment.

**Comment by AingLee** [comment]
Thanks for your advises. I have successfully built "extend_utils" and got the output of "_extend_utils.cpython-36m-x86_64-linux-gnu.so". However, I get into another issue after running "python lib/utils/data_utils.py" as following. I have tried to do "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lee/Desktop/research_code/pvnet/lib/utils/extend_utils/lib" (just type it in the terminal?), but it still did not work. Do you have any suggestions? 

File "lib/utils/data_utils.py", line 18, in <module>
    from lib.utils.extend_utils.extend_utils import farthest_point_sampling
  File "/home/lee/Desktop/research_code/pvnet/lib/utils/extend_utils/extend_utils.py", line 3, in <module>
    from lib.utils.extend_utils._extend_utils import lib, ffi
ImportError: libceres.so.1: cannot open shared object file: No such file or directory

**Comment by pengsida** [comment]
It is the path problem.
Please `echo $LD_LIBRARY_PATH` and list files under `pvnet/lib/utils/extend_utils/lib`.

**Comment by AingLee** [comment]
When I did "echo $LD_LIBRARY_PATH", I got nothing before doing this "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lee/Desktop/research_code/pvnet/lib/utils/extend_utils/lib", then I got ":/home/lee/Desktop/research_code/pvnet/lib/utils/extend_utils/lib". On the other hand, the list files under "pvnet/lib/utils/extend_utils/lib" are as following. I could not move these files by running "sh build_ceres.sh", I just copied these manually. What should I do next?
![Screenshot from 2019-10-15 15-55-28](https://user-images.githubusercontent.com/46101939/66812394-61058d80-ef65-11e9-87c3-98edc665e3c7.png)

**Comment by pengsida** [comment]
I never face this problem when I export LD_LIBRARY_PATH.
Check the softlink and if the path in `LD_LIBRARY_PATH` to `libceres.so.1` is correct.

**Comment by AingLee** [comment]
May I ask how you export the PATH? or what is your PATH? For me, I did like this "export PATH=/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/NsightCompute-2019.1${PATH:+:${PATH}}", so then I could built "extend_utils" without getting any errors.

**Comment by pengsida** [comment]
I add cuda path in `PATH`.
But this problem is not related to cuda.
`extend_utils` depends on `libceres.so.1` in https://github.com/zju3dv/pvnet/blob/master/lib/utils/extend_utils/build_extend_utils_cffi.py#L4
So when you use `extend_utils`, you need to add path to `libceres.so.1`.

**Comment by AingLee** [comment]
Hi, now I can run "python lib/utils/data_utils.py" with the nothing output. I solved this by uninstalling python 3.6.7 and then re-installing the python 3.6.8. However, right now, I am getting another issue when I run "python tools/demo.py", and get the error as following. Do you have any ideas? Thanks

    from lib.ransac_voting_gpu_layer.ransac_voting_gpu import ransac_voting_layer_v3
  File "/home/lee/Desktop/research_code/pvnet/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py", line 2, in <module>
    import lib.ransac_voting_gpu_layer.ransac_voting as ransac_voting
ImportError: /home/lee/Desktop/research_code/pvnet/lib/ransac_voting_gpu_layer/ransac_voting.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6detail20DynamicCUDAInterface20unchecked_set_deviceE

**Comment by AingLee** [comment]
Thank you very much. Now I can run "demo.py" successfully, and get the output with a new test image.
![new_cat](https://user-images.githubusercontent.com/46101939/66941198-fa719400-f078-11e9-9cf9-b4af16effaa9.png)

**Comment by pengsida** [comment]
The blue bounding box is our prediction, and the green one is the ground truth, whose coordinate need to be transformed.
