### ISSUE TITLE
uncertainty_pnp not working

### ISSUE THREAD

**Issue by DeepLearningGPE** [zju3dv/pvnet#94]
Hello,

i followed the steps in the README and installed GCC 5.4.0, build ceres, copied them into extend_utils/lib etc.
I also ran `python build_extend_utils_cffi.py` succesfully.
Now, when I try to run `train_linemod.py` with uncertainty_pnp, i get the error `Memory access error (memory dumped)`, caused by the line         `lib.uncertainty_pnp(points_2d_ptr,points_3d_ptr,weights_3d_ptr,camera_matrix_ptr,init_rt_ptr,result_rt_ptr,pn)` in class `extend_utils.py`.

How do I proceed from here?

Thanks in advance.

**Comment by pengsida** [comment]
I don't know.
Did you load the pretrained model correctly?

**Comment by DeepLearningGPE** [comment]
Thanks for your answer, yes the model works within the `demo.py` script and also within the `train_linemod.py` without uncertainty_pnp.

I get this output while building ceres, where some things fail or are not found:
`-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected Ceres version: 1.14.0 from /home/xxxx/Projects/pvnet/pvnet/ceres/ceres-solver-1.14.0/include/ceres/version.h
-- No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
-- Found installed version of Eigen: /usr/local/share/eigen3/cmake
-- Found Eigen: /usr/local/include/eigen3 (found version "3.3.7") 
-- Found Eigen version 3.3.7: /usr/local/include/eigen3
-- Enabling use of Eigen as a sparse linear algebra library.
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Found LAPACK library: /usr/lib/libopenblas.so;/usr/lib/libopenblas.so
-- A library with BLAS API found.
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found SUITESPARSEQR headers in: /usr/include/suitesparse
-- Found SUITESPARSEQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Found SUITESPARSE_CONFIG headers in: /usr/include/suitesparse
-- Found SUITESPARSE_CONFIG library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found LIBRT library: /usr/lib/x86_64-linux-gnu/librt.so
-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse: TRUE (found version "5.1.2") 
-- Found SuiteSparse 5.1.2, building with SuiteSparse.
-- Found CXSparse: /usr/include/suitesparse (found version "3.1.9") 
-- Found CXSparse version: 3.1.9, building with CXSparse.
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- Detected gflags version: 2.2.1
-- Found Gflags: /usr/include  
-- Found Google Flags header in: /usr/include, in namespace: google
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Glog: /usr/include  
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Building with OpenMP.
-- Performing Test COMPILER_HAS_CXX11_FLAG
-- Performing Test COMPILER_HAS_CXX11_FLAG - Success
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Performing Test CXX11_MATH_FUNCTIONS_FOUND
-- Performing Test CXX11_MATH_FUNCTIONS_FOUND - Failed
-- Building Ceres as a shared library.
-- No build type specified; defaulting to CMAKE_BUILD_TYPE=Release.
-- Creating configured Ceres config.h output directory: /home/xxxx/Projects/pvnet/pvnet/ceres/ceres-solver-1.14.0/build/config/ceres/internal
-- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
-- Enabling CERES_USE_OPENMP in Ceres config.h
-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
-- Enabling CERES_TR1_UNORDERED_MAP in Ceres config.h
-- Enabling CERES_TR1_MEMORY_HEADER in Ceres config.h
-- Enabling CERES_TR1_SHARED_PTR in Ceres config.h
-- Enabling CERES_USING_SHARED_LIBRARY in Ceres config.h
-- Build the examples.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxxx/Projects/pvnet/pvnet/ceres/ceres-solver-1.14.0/build
`
The building process ends without errors though.
Can this be the reason? I couldn't find out how to fix those parts.

**Comment by pengsida** [comment]
I don't know where the problem is.

**Comment by DeepLearningGPE** [comment]
After trying to debug with gdb, i encountered the same error as in #71 .
However, I can't really see a solution in the issue. Is there anything I can do?

**Comment by pengsida** [comment]
It's ceres problem.
I did not face this problem.

**Comment by pengsida** [comment]
I find the problem is caused by the ceres version.
`libceres.so.2.0.0` works fine.

**Comment by DeepLearningGPE** [comment]
Thanks for your suggestion. As far as I can see, the build process of ceres doesn't create a `libceres.so.2.0.0` file, i used the file you provided in the project to call `python build_extend_utils_cffi.py` and then called `train_linemod.py`, still got the same error.
Do you have any ideas?

**Comment by DeepLearningGPE** [comment]
Nevermind, had a wrong `libceres.2` but a right `libceres.2.0.0` file, it works! Thanks!

**Comment by zeal-github** [comment]
> Nevermind, had a wrong `libceres.2` but a right `libceres.2.0.0` file, fixed that and it works! Thanks!

Hi, how did you solve the problem? I used the build_ceres.sh scripts in this project to build ceres but did not got a libceres.2 or libceres.2.0.0.

**Comment by zeal-github** [comment]
@DeepLearningGPE 

> Nevermind, had a wrong `libceres.2` but a right `libceres.2.0.0` file, fixed that and it works! Thanks!

Hi, what do you mean in this line? How did you solve the problem? I use the build_ceres.sh scripts in this repo to build ceres but did not get a libceres.2 or libceres.2.0.0?
Can you explain more clearly? Thanks!

**Comment by DeepLearningGPE** [comment]
Hi, I only copied both files from the original repo and referenced them in `build_extend_utils_cffi.py` before running it, you don't need to call `build_ceres.sh` anymore.

**Comment by WW-0** [comment]
软连接出错，进入clean-pvnet-master/lib/csrc/uncertainty_pnp/lib/  删除libceres.so libceres.so.2
再执行命令：
ln -s libceres.so.2.0.0 libceres.so.2   
ln -s libceres.so.2.0.0 libceres.so.2 
重新创建软连接
再执行 python setup.py build_ext --inplace
