### ISSUE TITLE
段错误(吐核)

### ISSUE THREAD

**Issue by leansail** [zju3dv/pvnet#97]
能否帮忙看一下？多谢

相关的依赖库都编译成功了，执行python lib/utils/data_utils.py正常，执行python tools/demo.py报“段错误(吐核)”，gdb python core文件，打出如下信息：

Core was generated by `python tools/demo.py'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f297d91343c in construct<_object*, _object*> (__p=0xb, this=0x5593df6fb308) at /usr/include/c++/4.8.2/ext/new_allocator.h:120
120             { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.5.x86_64 libICE-1.0.9-9.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.5-2.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXrender-0.9.10-1.el7.x86_64 sssd-client-1.16.2-13.el7_6.8.x86_64 suitesparse-4.0.2-10.el7.x86_64

**Comment by leansail** [comment]
在gdb中输入bt命令，得到如下信息：

#0  0x00007f9f043d043c in construct<_object*, _object*> (__p=0xb, this=0x563c66e11308) at /usr/include/c++/4.8.2/ext/new_allocator.h:120
#1  _S_construct<_object*, _object*> (__p=0xb, __a=...) at /usr/include/c++/4.8.2/bits/alloc_traits.h:254
#2  construct<_object*, _object*> (__p=0xb, __a=...) at /usr/include/c++/4.8.2/bits/alloc_traits.h:393
#3  emplace_back<_object*> (this=0x563c66e11308) at /usr/include/c++/4.8.2/bits/vector.tcc:96
#4  push_back (
    __x=<unknown type in /home/PycharmProjects/pvnet/lib/ransac_voting_gpu_layer/ransac_voting.cpython-37m-x86_64-linux-gnu.so, CU 0x0, DIE 0x13ecca>, 
    this=0x563c66e11308) at /usr/include/c++/4.8.2/bits/stl_vector.h:920
#5  loader_life_support (this=0x7ffe0747ff20) at /root/miniconda3/lib/python3.7/site-packages/torch/include/pybind11/cast.h:44
#6  pybind11::cpp_function::dispatcher (self=<optimized out>, args_in=0x7f9e958e6750, kwargs_in=0x0)
    at /root/miniconda3/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:619
#7  0x0000563c64ca76e4 in _PyMethodDef_RawFastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:690
#8  0x0000563c64ca7801 in _PyCFunction_FastCallKeywords (func=0x7f9f04479828, args=args@entry=0x563c67d08320, nargs=nargs@entry=3, 
    kwnames=kwnames@entry=0x0) at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:730
#9  0x0000563c64d032bc in call_function (kwnames=0x0, oparg=3, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4568
#10 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3093
#11 0x0000563c64c444f9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#12 0x0000563c64ca6a27 in _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:433
#13 0x0000563c64cff8fe in call_function (kwnames=0x7f9f192a7ac8, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#14 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3139
#15 0x0000563c64c444f9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#16 0x0000563c64c455d5 in _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#17 0x0000563c64c45966 in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
#18 0x0000563c64c5cc43 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#19 0x0000563c64c5195e in PyObject_Call () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:245
#20 0x0000563c64d00250 in do_call_core (kwdict=0x7f9e9595ae10, callargs=0x7f9e9595dc48, func=0x7f9f208f4cc8)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4645
#21 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3191
#22 0x0000563c64c444f9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#23 0x0000563c64c455d5 in _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#24 0x0000563c64c45966 in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
#25 0x0000563c64c5cc43 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#26 0x0000563c64c9f16a in slot_tp_call () at /tmp/build/80754af9/python_1553721932202/work/Objects/typeobject.c:6379
#27 0x0000563c64c5195e in PyObject_Call () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:245
#28 0x0000563c64d00250 in do_call_core (kwdict=0x7f9e9599dcf0, callargs=0x7f9e9595db88, func=0x7f9e958e18d0)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4645
#29 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3191
#30 0x0000563c64c444f9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#31 0x0000563c64c455d5 in _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#32 0x0000563c64c45966 in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
---Type <return> to continue, or q <return> to quit---
#33 0x0000563c64c5cc43 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#34 0x0000563c64c5195e in PyObject_Call () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:245
#35 0x0000563c64d00250 in do_call_core (kwdict=0x7f9e958e6558, callargs=0x7f9e958ecc48, func=0x7f9f20811688)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4645
#36 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3191
#37 0x0000563c64c444f9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#38 0x0000563c64c455d5 in _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:376
#39 0x0000563c64c45966 in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:98
#40 0x0000563c64c5cc43 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:904
#41 0x0000563c64c9f16a in slot_tp_call () at /tmp/build/80754af9/python_1553721932202/work/Objects/typeobject.c:6379
#42 0x0000563c64ca7d2b in _PyObject_FastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:199
#43 0x0000563c64d03026 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4619
#44 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#45 0x0000563c64ca679b in function_code_fastcall (globals=<optimized out>, nargs=0, args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:283
#46 _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1553721932202/work/Objects/call.c:408
#47 0x0000563c64cfe846 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:4616
#48 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3124
#49 0x0000563c64c444f9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3930
#50 0x0000563c64c453c4 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:3959
#51 0x0000563c64c453ec in PyEval_EvalCode (co=co@entry=0x7f9f207d01e0, globals=globals@entry=0x7f9f20843240, locals=locals@entry=0x7f9f20843240)
    at /tmp/build/80754af9/python_1553721932202/work/Python/ceval.c:524
#52 0x0000563c64d5d874 in run_mod () at /tmp/build/80754af9/python_1553721932202/work/Python/pythonrun.c:1035
#53 0x0000563c64d67b81 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1553721932202/work/Python/pythonrun.c:988
#54 0x0000563c64d67d73 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1553721932202/work/Python/pythonrun.c:429
#55 0x0000563c64d67e3d in PyRun_AnyFileExFlags () at /tmp/build/80754af9/python_1553721932202/work/Python/pythonrun.c:84
#56 0x0000563c64d68e5f in pymain_run_file (p_cf=0x7ffe07481640, filename=0x563c65e852f0 L"tools/demo.py", fp=0x563c65efe460)
    at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:427
#57 pymain_run_filename (cf=0x7ffe07481640, pymain=0x7ffe07481750) at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:1627
#58 pymain_run_python (pymain=0x7ffe07481750) at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:2877
#59 pymain_main () at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:3038
#60 0x0000563c64d68f7c in _Py_UnixMain () at /tmp/build/80754af9/python_1553721932202/work/Modules/main.c:3073
#61 0x00007f9f201823d5 in __libc_start_main () from /lib64/libc.so.6
#62 0x0000563c64d0e122 in _start () at ../sysdeps/x86_64/elf/start.S:103

**Comment by pengsida** [comment]
gcc要用5.4的。
